import { canonicalRequestStatus } from "../../../shared/workflowStatus.mjs";
import { useLanguage } from "../context/LanguageContext.jsx";

const classes = {
  BORRADOR: "badge badge-gray",
  EN_VALIDACION: "badge badge-blue",
  ENVIADO: "badge badge-blue",
  PENDIENTE_APROBACION: "badge badge-amber",
  OBSERVADO: "badge badge-amber",
  OBSERVADO_PRESUPUESTO: "badge badge-amber",
  OBSERVADO_SUNAT: "badge badge-amber",
  OBSERVADO_MONTO_EXCEDIDO: "badge badge-amber",
  OBSERVADO_CARGA_MASIVA: "badge badge-amber",
  PAGO_REBOTADO: "badge badge-red",
  PAGADO_CERRADO: "badge badge-dark",
  DEVUELTO: "badge badge-amber",
  APROBADO: "badge badge-blue",
  APROBADO_DIRECTOR: "badge badge-blue",
  APROBADO_VICERRECTOR: "badge badge-blue",
  COMPROMISO_PRESUPUESTAL: "badge badge-amber",
  CONTABILIZADO: "badge badge-blue",
  PROVISIONADO_CXP: "badge badge-indigo",
  PROGRAMADO: "badge badge-blue",
  RECHAZADO: "badge badge-red",
  TXT_GENERADO: "badge badge-indigo",
  PAGADO: "badge badge-green",
  CONCILIADO: "badge badge-green",
  RENDICION_PENDIENTE: "badge badge-amber",
  CERRADO: "badge badge-dark",
  ANULADO: "badge badge-red",
  PENDING_VALIDATION: "badge badge-amber",
  OBSERVED: "badge badge-amber",
  TRANSITIONAL: "badge badge-gray",
  ACTIVE: "badge badge-green",
  RESERVED: "badge badge-amber",
  COMMITTED: "badge badge-amber",
  NO_BUDGET: "badge badge-gray",
  AVAILABLE: "badge badge-green",
  CLOSED_BUDGET: "badge badge-dark",
  WITHOUT_BUDGET: "badge badge-gray",
  EXECUTED: "badge badge-green",
  PARTIALLY_EXECUTED: "badge badge-amber",
  PARTIALLY_PAID: "badge badge-amber",
  PAID: "badge badge-green",
  RELEASED: "badge badge-blue",
  HOMOLOGATED: "badge badge-green",
  VERIFIED: "badge badge-green",
  MATCH: "badge badge-green",
  MANUAL_ACCEPTED: "badge badge-blue",
  LEGACY_ACCEPTED: "badge badge-gray",
  MISMATCH: "badge badge-red",
  NOT_REVIEWED: "badge badge-gray",
  NOT_VERIFIED: "badge badge-gray",
  YES: "badge badge-amber",
  NO: "badge badge-green",
  NOT_DECLARED: "badge badge-gray",
  INACTIVE: "badge badge-gray",
  COMPLIANT: "badge badge-green",
  NON_COMPLIANT: "badge badge-red",
  SCHEDULED: "badge badge-blue",
  PAYMENT_FILE_CREATED: "badge badge-indigo",
  CANCELLED: "badge badge-red",
  VALIDATED: "badge badge-green",
  VALID: "badge badge-green",
  EXPORTED: "badge badge-blue",
  MANUAL_REVIEW: "badge badge-amber",
  MISSING_VOUCHER_LINK: "badge badge-red",
  PENDING: "badge badge-amber",
  APPROVED: "badge badge-green",
  REJECTED: "badge badge-red",
  BLOCKED: "badge badge-red",
  COMPLETED: "badge badge-green",
  COMPLETED_WITH_OBSERVATIONS: "badge badge-amber",
  QUEUED: "badge badge-blue",
  PROCESSING: "badge badge-indigo",
  PROVISIONED: "badge badge-green",
  OBSERVED_SUNAT: "badge badge-amber",
  OBSERVED_DUPLICATE: "badge badge-amber",
  OBSERVED_AMOUNT_EXCEEDED: "badge badge-amber",
  OBSERVED_BATCH: "badge badge-amber",
  PAYMENT_BOUNCED: "badge badge-red",
  A1: "badge badge-blue",
  A2: "badge badge-indigo",
  B: "badge badge-amber",
  C: "badge badge-green",
  NORMAL: "badge badge-gray",
  PRIORITY: "badge badge-red",
  OPEN: "badge badge-blue",
  RESOLVED: "badge badge-green",
  DISMISSED: "badge badge-gray",
  GENERATED: "badge badge-indigo",
  PARTIALLY_CONFIRMED: "badge badge-amber",
  CONFIRMED: "badge badge-green",
  NOT_REQUIRED: "badge badge-gray",
  SUBMITTED: "badge badge-blue",
  DEMO: "badge badge-amber",
  OVERDUE: "badge badge-red",
  SLA_DUE_SOON: "badge badge-amber",
  SLA_OVERDUE: "badge badge-red",
  SLA_ESCALATION: "badge badge-red",
  REIMBURSEMENT: "badge badge-blue",
  PAYROLL_DEDUCTION: "badge badge-indigo"
};

export default function StatusBadge({ status }) {
  if (status !== "RENDICION_PENDIENTE") status = canonicalRequestStatus(status);
  const { t } = useLanguage();
  return <span className={classes[status] || "badge badge-gray"}><span className="badge-label">{t(status || "N/A")}</span></span>;
}
