import { mockWorkDrafts } from "./mockWorkDrafts.mjs";
import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";
import { chromium } from "playwright";

const root = fileURLToPath(new URL("../", import.meta.url));
const output = fileURLToPath(new URL("../../.tmp/budget-experience/", import.meta.url));
await mkdir(output, { recursive: true });
const server = await createServer({ root, configFile: `${root}/vite.config.js`, server: { host: "127.0.0.1", port: 5194, strictPort: true }, logLevel: "error" });
await server.listen();
let browser;
try {
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, colorScheme: "light" });
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  const user = { _id: "sim-user", name: "UMA Requester", role: "Solicitor", area: "Purchasing", costCenter: "center" };
  const center = { _id: "center", code: "CC-100", name: "Teaching and learning", active: true };
  const expense = { _id: "expense", code: "EXP-100", name: "Supplies", category: "OPEX", accountingClass: "CLASS_6", accountNumber: "603201", active: true };
  const supplier = { _id: "supplier", name: "Supplier One", legalName: "Supplier One", rucDni: "20600000001", active: true, homologationStatus: "HOMOLOGATED" };
  const form = { flowType: "A1", requestType: "OPEX", expenseNature: "GOODS", priority: "MEDIA", requesterCostCenter: "center", schoolOrDepartment: "Purchasing", issueDate: "2026-09-04", accountingPeriod: "2026-09", currency: "PEN", supplier: "supplier", title: "Teaching supplies", detailedDescription: "Supplies for practical classes", businessJustification: "Continue teaching", nonApprovalRisk: "Class delays", description: "Teaching supplies", supplierSelectionReason: "Approved supplier" };
  const line = { clientId: "line", itemDescription: "Teaching supplies", quantity: "3", unitOfMeasure: "UNIT", unitPrice: "1000", priceIncludesIGV: true, costCenter: "center", expenseType: "expense", netAmount: 2542.37, igvAmount: 457.63, totalAmount: 3000 };
  let requests = [], fail = false;
  await page.route(url => url.pathname.startsWith("/api/"), async route => {
    const path = new URL(route.request().url()).pathname.replace("/api", "");
    let body = { data: [] };
    if (path === "/auth/me") body = { user };
    else if (path === "/requests/authorized-cost-centers") body = { data: [center] };
    else if (path === "/expense-types") body = { data: [expense] };
    else if (path === "/suppliers") body = { data: [supplier] };
    else if (path === "/employee-bank-accounts") body = { data: [{ _id: "bank-1", user, bank: "BCP", currency: "PEN", active: true, verificationStatus: "PENDING", preferred: true, accountNumberMasked: "******1234", cciMasked: "****************1234" }] };
    else if (path === "/accounting-periods") body = { data: [{ _id: "period", period: "2026-09", status: "OPEN" }] };
    else if (path === "/notifications") body = { data: [], unreadCount: 0 };
    else if (path === "/dashboard/tasks") body = { items: [], total: 0, counters: {} };
    else if (path === "/requests/form-policy") body = { data: { documentRequirements: [], quotationPolicy: { enabled: false } } };
    else if (path === "/requests/budget-preview") {
      const payload = route.request().postDataJSON();
      requests.push(payload);
      if (fail) return route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ message: "Unavailable" }) });
      const amount = payload.lines.reduce((sum, line) => sum + Number(line.totalAmount), 0);
      const period = payload.scenario?.period || payload.accountingPeriod;
      const monthly = period.endsWith("10") ? 2500 : 8000;
      const annual = period.startsWith("2027");
      body = { data: { status: !annual && amount > monthly ? "INSUFFICIENT" : "AVAILABLE", totalRequested: amount, period, asOf: new Date().toISOString(), lines: [{ costCenter: "center", expenseType: "expense", costCenterSnapshot: center, allocation: "plan", planningMode: annual ? "ANNUAL_ONLY" : "ANNUAL_MONTHLY", mode: "ACTIVE", amount, annualAvailable: 50000, annualProjected: 50000-amount, monthlyAvailable: annual ? null : monthly, monthlyProjected: annual ? null : monthly-amount, available: monthly, projectedBalance: monthly-amount }] } };
    } else if (route.request().method() !== "GET") throw new Error(`Unexpected mutation ${path}`);
    await route.fulfill({ contentType: "application/json", body: JSON.stringify(body) });
  });
  await mockWorkDrafts(page);
  await page.addInitScript(({ user, form, line }) => {
    localStorage.setItem("erp_user", JSON.stringify(user)); localStorage.setItem("erp_token", "test-token"); localStorage.setItem("erp_language", "en");
    if (!localStorage.getItem("sim-initialized")) {
      localStorage.setItem("sim-initialized", "true");
      localStorage.setItem(`erp_request_autosave_${user._id}_new`, JSON.stringify({ form, lines: [line], quotations: [], savedAt: new Date().toISOString() }));
    }
  }, { user, form, line });
  await page.goto("http://127.0.0.1:5194/requests/new");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  const sim = page.locator(".remaining-budget");
  await sim.locator(".remaining-budget-source").waitFor();
  await sim.getByText("PEN 47,000.00", { exact: true }).waitFor();
  await sim.getByText("PEN 5,000.00", { exact: true }).waitFor();
  assert.equal(await sim.locator('input, select').count(), 0, "Remaining budget has no simulation controls");
  assert.ok((await sim.boundingBox()).height < 280, "Summary stays compact");
  await page.locator('.request-item-card').getByRole('spinbutton', { name: /Unit price/ }).fill('3000');
  await sim.getByText(/Budget shortfall:.*1,000\.00/).waitFor();
  assert.match(await sim.innerText(), /Budget shortfall/);
  await page.locator('.request-item-card').getByRole('spinbutton', { name: /Unit price/ }).fill('1000');
  await sim.getByText("PEN 5,000.00", { exact: true }).waitFor();
  fail = true;
  await sim.getByRole('button', { name: 'Refresh balances' }).click();
  await sim.getByRole('alert').waitFor();
  fail = false;
  await sim.getByRole('button', { name: 'Refresh balances' }).click();
  await sim.getByText("PEN 5,000.00", { exact: true }).waitFor();
  assert.ok(requests.every(payload => !payload.scenario), "Only actual request amounts are previewed");
  await sim.screenshot({ animations: "disabled", path: `${output}/remaining-light.png` });
  await page.getByRole("button", { name: "Account menu", exact: true }).click();
  await page.getByRole("combobox", { name: "Appearance", exact: true }).selectOption("dark");
  assert.equal(await page.locator("html").getAttribute("data-theme"), "dark");
  await page.getByRole("button", { name: "Account menu", exact: true }).click();
  await sim.screenshot({ animations: "disabled", path: `${output}/remaining-dark.png` });
  await page.setViewportSize({ width: 390, height: 844 });
  await sim.scrollIntoViewIfNeeded();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await sim.screenshot({ animations: "disabled", path: `${output}/remaining-mobile.png` });
  await page.emulateMedia({ reducedMotion: "reduce" });
  assert.equal(await sim.locator(".remaining-budget-bar").first().evaluate(element => getComputedStyle(element).animationName), "none");
  await page.reload();
  assert.equal(await page.locator("html").getAttribute("data-theme"), "dark", "Appearance survives reload");
  await page.getByRole("button", { name: "Account menu", exact: true }).click();
  await page.getByRole("combobox", { name: "Appearance", exact: true }).selectOption("system");
  await page.emulateMedia({ colorScheme: "light" });
  await page.waitForFunction(() => document.documentElement.dataset.theme === "light");
  await page.emulateMedia({ colorScheme: "dark" });
  await page.waitForFunction(() => document.documentElement.dataset.theme === "dark");
  await page.setViewportSize({ width: 1440, height: 1100 });
  await page.goto("http://127.0.0.1:5194/reimbursement-bank");
  await page.getByText("******1234", { exact: true }).first().waitFor();
  await page.screenshot({ animations: "disabled", path: `${output}/banking-dark.png`, fullPage: true });
  await page.getByRole("button", { name: "Add bank profile", exact: true }).click();
  await page.locator(".drawer").waitFor();
  assert.notEqual(await page.locator(".drawer").evaluate(element => getComputedStyle(element).backgroundColor), "rgb(255, 255, 255)");
  await page.screenshot({ animations: "disabled", path: `${output}/banking-drawer-dark.png` });
  const login = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  await login.goto("http://127.0.0.1:5194/login");
  await login.getByRole("combobox", { name: "Appearance", exact: true }).selectOption("dark");
  await login.screenshot({ animations: "disabled", path: `${output}/login-dark.png` });
  await login.setViewportSize({ width: 390, height: 844 });
  assert.equal(await login.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await login.screenshot({ animations: "disabled", path: `${output}/login-mobile-dark.png`, fullPage: true });
  assert.deepEqual(errors, []);
  console.log("Compact remaining balances, automatic amount updates, shortfalls, refresh errors, no scenario controls, themes and mobile checks passed.");
} finally { await browser?.close(); await server.close(); }
