import assert from "node:assert/strict";import {createServer} from "vite";import {chromium} from "playwright";import {fileURLToPath} from "node:url";
const root=fileURLToPath(new URL("../",import.meta.url));const server=await createServer({root,server:{host:"127.0.0.1",port:5199,strictPort:true},logLevel:"error"});await server.listen();let browser;
try{browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on("pageerror",e=>errors.push(e.message));await page.addInitScript(()=>{window.motionCalls=[];const original=Element.prototype.animate;Element.prototype.animate=function(frames,options){window.motionCalls.push({frames,options});return original.call(this,frames,options);};});await page.goto("http://127.0.0.1:5199/test/motion.fixture.html");
await page.getByLabel("Retained value").fill("Unsubmitted work");await page.getByRole("button",{name:"Next",exact:true}).click();await page.getByRole("button",{name:"Back",exact:true}).click();assert.equal(await page.getByLabel("Retained value").inputValue(),"Unsubmitted work");assert.ok(await page.evaluate(()=>motionCalls.some(call=>call.frames[0].transform==="translateX(-10px)")));
await page.getByText("Native details",{exact:true}).click();await page.getByText("Expanded information").waitFor();await page.getByText("Native details",{exact:true}).click();await page.getByText("Expanded information").waitFor({state:"hidden"});
await page.getByRole("button",{name:"Toggle section"}).click();await page.getByLabel("Section value").fill("Keep me");await page.getByRole("button",{name:"Toggle section"}).click();await page.getByLabel("Section value").waitFor({state:"hidden"});await page.getByRole("button",{name:"Toggle section"}).click();assert.equal(await page.getByLabel("Section value").inputValue(),"Keep me");
await page.getByRole("button",{name:"Add item"}).click();await page.getByRole("button",{name:"Remove 1",exact:true}).click();await page.waitForFunction(()=>!document.querySelector('body > [inert]'));assert.equal(await page.locator(".request-item-card").count(),1);
await page.getByRole("button",{name:"Save",exact:true}).click();await page.locator("button[aria-busy=true]").waitFor();await page.getByRole("button",{name:"Save",exact:true}).waitFor();
await page.getByRole("button",{name:"Second tab"}).click();await page.waitForFunction(()=>document.querySelector(".analytics-tabs").style.getPropertyValue("--tab-width")!=="");
await page.emulateMedia({reducedMotion:"reduce"});await page.evaluate(()=>motionCalls.length=0);await page.getByRole("button",{name:"Next",exact:true}).click();await page.getByRole("button",{name:"Add item"}).click();await page.getByText("Native details",{exact:true}).click();assert.equal(await page.evaluate(()=>motionCalls.length),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log("PASS: direction, retained fields, expand/collapse, item removal, busy feedback, tabs and reduced motion.");}finally{await browser?.close();await server.close();}
