import React from "react";
import PadronStatus from "../src/components/PadronStatus.jsx";
import { createRoot } from "react-dom/client";
import { LanguageProvider } from "../src/context/LanguageContext.jsx";
import DataTable from "../src/components/DataTable.jsx";
import QuotationComparison from "../src/components/QuotationComparison.jsx";
import SectionNavigation from "../src/components/SectionNavigation.jsx";
import "../src/styles/global.css";
import "../src/styles/uma.css";
import "../src/styles/experience.css";
import "../src/styles/responsive.css";
const columns = [{ key: "name", label: "Supplier" }, { key: "ruc", label: "RUC" }, { key: "amount", label: "Amount" }, { key: "status", label: "Status" }, { key: "reference", label: "Reference" }, { key: "contact", label: "Contact", render: () => <button onClick={() => document.body.dataset.edited = "yes"}>Edit contact</button> }];
createRoot(document.getElementById("root")).render(<LanguageProvider><main style={{padding: 16, maxWidth: 1200, margin: "auto"}}><SectionNavigation aria-label="Sections"><a href="#results">Results</a><a href="#quotes">Quotations</a></SectionNavigation><PadronStatus /><section id="results"><DataTable columns={columns} rows={[{_id:"one", name:"A long supplier company name for responsive verification", ruc:"20123456789", amount:"PEN 300,000.00", status:"Pending accounting verification", reference:"Long-reference-".repeat(12)}]} selection={{selected:[],onChange:()=>{}}} exportable rowActions={[{label:"Open",onClick:()=>{}}]} /></section><section id="quotes"><QuotationComparison suppliers={[{_id:"s", name:"Supplier name"}]} quotations={[{clientId:"q",supplier:"s",amount:3540,currency:"PEN",deliveryPeriod:"Within fifteen business days", paymentCondition:"ADVANCE_BALANCE",advancePercentage:30}]} /></section></main></LanguageProvider>);
