import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
const source = (p) => readFileSync(fileURLToPath(new URL(p, import.meta.url)), "utf8");
const app = source("../src/App.jsx");
const bulk = source("../src/pages/BulkInvoiceUpload.jsx");
const observations = source("../src/pages/InvoiceObservations.jsx");
const treasury = source("../src/pages/TreasuryQueue.jsx");
const rendition = source("../src/components/rendition/OfficialRenditionWorkspace.jsx");
assert.match(app, /batch-invoices/);
assert.match(app, /invoice-observations/);
assert.match(bulk, /Valid invoices will continue even when another invoice is observed/);
assert.match(observations, /responseType: "blob"/);
assert.match(treasury, /payableIds: selected/);
assert.match(treasury, /\/payables\/\$\{payableIdOf\(paymentRow\)\}\/confirm-payment/);
assert.match(treasury, /\/bounce/);
assert.match(treasury, /cciLetter/);
assert.match(rendition, /settle-non-deductible/);
assert.match(rendition, /Rendition overdue/);
console.log("PASS Triple-track frontend contracts");
