export default {
  "SUNAT lookup last checked": "�ltima consulta a SUNAT",
  "Browser backup is unavailable. Keep this page open until your draft is saved to your account.": "El respaldo del navegador no est� disponible. Mant�n esta p�gina abierta hasta que el borrador se guarde en tu cuenta.",
  "Passwords are not saved in drafts. Enter them when creating or updating the user.": "Las contrase�as no se guardan en los borradores. Ingr�salas al crear o actualizar el usuario.",
  "Loading saved work...": "Cargando trabajo guardado...",
  "Progress saves automatically": "Tu progreso se guarda automáticamente",
  "Unsaved changes": "Cambios pendientes de guardar",
  "Saving draft...": "Guardando borrador...",
  "Draft saved to your account": "Borrador guardado en tu cuenta",
  "Saved work restored": "Trabajo guardado recuperado",
  "Not saved — check your connection": "Sin guardar: revisa tu conexión",
  "Saved work could not be loaded": "No se pudo cargar el trabajo guardado",
  "This draft changed in another session": "Este borrador cambió en otra sesión",
  "The original record changed. Review restored values before submitting.": "El registro original cambió. Revisa los datos recuperados antes de enviar.",
  "Private draft · Closing keeps your progress · Submission is still required": "Borrador privado · Cerrar conserva tu progreso · Aún debes enviarlo",
  "Last saved": "Último guardado",
  "Discard draft": "Descartar borrador",
  "Keep draft": "Conservar borrador",
  "Load saved version": "Cargar versión guardada",
  "Keep as separate draft": "Conservar como otro borrador",
  "Start another draft": "Iniciar otro borrador",
  "Delete this unfinished draft and its attachments?": "¿Eliminar este borrador y sus archivos adjuntos?",
  "Continue your work": "Continúa tu trabajo",
  "Unfinished work saved privately to your account.": "Trabajo pendiente guardado de forma privada en tu cuenta.",
  "Show all drafts": "Ver todos los borradores",
  "Show less": "Ver menos",
  "Financial request": "Solicitud financiera",
  "Supplier proposal": "Propuesta de proveedor",
  "Reimbursement bank profile": "Perfil bancario de reembolso",
  "Annual budget plan": "Plan de presupuesto anual",
  "Budget adjustment": "Ajuste de presupuesto",
  "Fiscal processing": "Procesamiento contable",
  "Expense rendition": "Rendición de gastos",
  "Rendition settlement": "Regularización de rendición",
  "Batch invoice upload": "Carga masiva de comprobantes",
  "Invoice correction files": "Archivos de corrección de comprobante",
  "Invoice and conformity files": "Archivos de factura y conformidad",
  "Supplier bank account": "Cuenta bancaria del proveedor",
  "Supplier review notes": "Notas de revisión del proveedor",

  "Remaining budget": "Presupuesto restante",
  "Balance after this request. No funds are reserved here.": "Saldo después de esta solicitud. No se reservan fondos aquí.",
  "Annual remaining": "Saldo anual", "Monthly remaining": "Saldo mensual",
  "This request": "Esta solicitud", "Updating balances…": "Actualizando saldos…",
  "Add the USD/PEN exchange rate for the request date to see the remaining budget.": "Registra el tipo de cambio USD/PEN para la fecha de la solicitud y podrás ver el saldo restante.",
  "Appearance": "Apariencia", "System": "Sistema", "Light": "Claro", "Dark": "Oscuro",
  "Plan before you submit": "Planifica antes de enviar",
  "If this is approved…": "Si se aprueba esta solicitud…",
  "Compare an amount and month without changing your request or reserving funds.": "Compara un importe y un mes sin modificar tu solicitud ni reservar fondos.",
  "Reset scenario": "Restablecer escenario",
  "Refresh balances": "Actualizar saldos",
  "Budget information could not be refreshed. Check the request fields and try again.": "No se pudo actualizar el presupuesto. Revisa los campos de la solicitud e inténtalo de nuevo.",
  "Scenario amount (% of request)": "Importe del escenario (% de la solicitud)",
  "Scenario percentage slider": "Porcentaje del escenario",
  "Budget month": "Mes presupuestal",
  "Choose a valid month and a percentage from 1 to 300.": "Selecciona un mes válido y un porcentaje entre 1 y 300.",
  "Calculating budget impact…": "Calculando el impacto presupuestal…",
  "The scenario could not be calculated. Try again.": "No se pudo calcular el escenario. Inténtalo de nuevo.",
  "Add the USD/PEN exchange rate for the request date to see the simulation.": "Registra el tipo de cambio USD/PEN para la fecha de la solicitud y podrás ver la simulación.",
  "Original request · PEN": "Solicitud original · PEN",
  "Scenario · PEN": "Escenario · PEN",
  "Scenario spend": "Gasto del escenario", "Remaining": "Disponible", "Shortfall": "Déficit",
  "Available now": "Disponible ahora", "Budget shortfall": "Déficit presupuestal",
  "Remaining after scenario": "Disponible después del escenario",
  "Remaining with original request": "Disponible con la solicitud original",
  "Annual budget": "Presupuesto anual", "Monthly budget": "Presupuesto mensual",
  "Available budget": "Presupuesto disponible",
  "Informational budget only. This balance is not an enforced spending limit.": "Presupuesto informativo. Este saldo no constituye un límite obligatorio de gasto.",
  "Annual-only plan: no separate monthly limit.": "Plan anual: no tiene un límite mensual independiente.",
  "Advances commit their expense budget at rendition. This is a planning estimate, not a commitment on approval.": "Las entregas a rendir comprometen el presupuesto de gasto en la rendición. Esta es una estimación de planificación, no un compromiso al aprobar.",
  "Availability is checked again when the request reaches budget commitment.": "La disponibilidad se vuelve a validar al registrar el compromiso presupuestal.",
  "All balances are in PEN, using the recorded exchange rate for the request date.": "Todos los saldos están en PEN, con el tipo de cambio registrado para la fecha de la solicitud.",
  "Calculated at": "Calculado a las"
};
