export default {
  "Updater": "Actualizador",
  "Running": "En ejecución",
  "Not running": "No está en ejecución",
  "Next check": "Próxima comprobación",
  "Preparation pending": "Preparación pendiente",
  "Expired": "Vencido",
  "Update pending": "Actualización pendiente",
  "Dataset date": "Fecha del padrón",
  "Last successful check": "Última comprobación exitosa",
  "Update status": "Estado de actualización",
  "Indexed records": "Registros indexados",
  "Last update activity": "Última actividad",
  "Updates run separately. Missing or expired data does not bypass taxpayer validation.": "Las actualizaciones se ejecutan por separado. Los datos ausentes o vencidos no omiten la validación tributaria.",
  "CHECKING": "Comprobando",
  "DOWNLOADING": "Descargando",
  "INDEXING": "Indexando",
  "BUILDING_SEARCH_INDEX": "Preparando índice de búsqueda",
  "READY": "Listo",
  "FAILED": "Error",
  "IDLE": "En espera",

  "Sort descending": "Orden descendente",
  "Sort ascending": "Orden ascendente",
  "About this section": "Acerca de esta sección",
  "Table options": "Opciones de tabla",
  "Draft options": "Opciones del borrador",
  "About this page": "Acerca de esta página",
  "View workflow": "Ver flujo de aprobación",
  "Go to section": "Ir a sección",
  "Section": "Sección",
  "Saved": "Guardado",
  "Sort by": "Ordenar por",
  "Schedule and confirm payments.": "Programa y confirma pagos.",
  "SUNAT lookup last checked": "Última consulta a SUNAT",
  "Browser backup is unavailable. Keep this page open until your draft is saved to your account.": "El respaldo del navegador no está disponible. Mantén esta página abierta hasta que el borrador se guarde en tu cuenta.",
  "Passwords are not saved in drafts. Enter them when creating or updating the user.": "Las contraseñas no se guardan en los borradores. Ingrésalas al crear o actualizar el usuario.",
  "Loading saved work...": "Cargando trabajo guardado...",
  "Progress saves automatically": "Tu progreso se guarda automÃ¡ticamente",
  "Unsaved changes": "Cambios pendientes de guardar",
  "Saving draft...": "Guardando borrador...",
  "Draft saved to your account": "Borrador guardado en tu cuenta",
  "Saved work restored": "Trabajo guardado recuperado",
  "Not saved â€” check your connection": "Sin guardar: revisa tu conexiÃ³n",
  "Saved work could not be loaded": "No se pudo cargar el trabajo guardado",
  "This draft changed in another session": "Este borrador cambiÃ³ en otra sesiÃ³n",
  "The original record changed. Review restored values before submitting.": "El registro original cambiÃ³. Revisa los datos recuperados antes de enviar.",
  "Private draft Â· Closing keeps your progress Â· Submission is still required": "Borrador privado Â· Cerrar conserva tu progreso Â· AÃºn debes enviarlo",
  "Last saved": "Ãšltimo guardado",
  "Discard draft": "Descartar borrador",
  "Keep draft": "Conservar borrador",
  "Load saved version": "Cargar versiÃ³n guardada",
  "Keep as separate draft": "Conservar como otro borrador",
  "Start another draft": "Iniciar otro borrador",
  "Delete this unfinished draft and its attachments?": "Â¿Eliminar este borrador y sus archivos adjuntos?",
  "Continue your work": "ContinÃºa tu trabajo",
  "Unfinished work saved privately to your account.": "Trabajo pendiente guardado de forma privada en tu cuenta.",
  "Show all drafts": "Ver todos los borradores",
  "Show less": "Ver menos",
  "Financial request": "Solicitud financiera",
  "Supplier proposal": "Propuesta de proveedor",
  "Reimbursement bank profile": "Perfil bancario de reembolso",
  "Annual budget plan": "Plan de presupuesto anual",
  "Budget adjustment": "Ajuste de presupuesto",
  "Fiscal processing": "Procesamiento contable",
  "Expense rendition": "RendiciÃ³n de gastos",
  "Rendition settlement": "RegularizaciÃ³n de rendiciÃ³n",
  "Batch invoice upload": "Carga masiva de comprobantes",
  "Invoice correction files": "Archivos de correcciÃ³n de comprobante",
  "Invoice and conformity files": "Archivos de factura y conformidad",
  "Supplier bank account": "Cuenta bancaria del proveedor",
  "Supplier review notes": "Notas de revisiÃ³n del proveedor",

  "Remaining budget": "Presupuesto restante",
  "Balance after this request. No funds are reserved here.": "Saldo despuÃ©s de esta solicitud. No se reservan fondos aquÃ­.",
  "Annual remaining": "Saldo anual", "Monthly remaining": "Saldo mensual",
  "This request": "Esta solicitud", "Updating balancesâ€¦": "Actualizando saldosâ€¦",
  "Add the USD/PEN exchange rate for the request date to see the remaining budget.": "Registra el tipo de cambio USD/PEN para la fecha de la solicitud y podrÃ¡s ver el saldo restante.",
  "Appearance": "Apariencia", "System": "Sistema", "Light": "Claro", "Dark": "Oscuro",
  "Plan before you submit": "Planifica antes de enviar",
  "If this is approvedâ€¦": "Si se aprueba esta solicitudâ€¦",
  "Compare an amount and month without changing your request or reserving funds.": "Compara un importe y un mes sin modificar tu solicitud ni reservar fondos.",
  "Reset scenario": "Restablecer escenario",
  "Refresh balances": "Actualizar saldos",
  "Budget information could not be refreshed. Check the request fields and try again.": "No se pudo actualizar el presupuesto. Revisa los campos de la solicitud e intÃ©ntalo de nuevo.",
  "Scenario amount (% of request)": "Importe del escenario (% de la solicitud)",
  "Scenario percentage slider": "Porcentaje del escenario",
  "Budget month": "Mes presupuestal",
  "Choose a valid month and a percentage from 1 to 300.": "Selecciona un mes vÃ¡lido y un porcentaje entre 1 y 300.",
  "Calculating budget impactâ€¦": "Calculando el impacto presupuestalâ€¦",
  "The scenario could not be calculated. Try again.": "No se pudo calcular el escenario. IntÃ©ntalo de nuevo.",
  "Add the USD/PEN exchange rate for the request date to see the simulation.": "Registra el tipo de cambio USD/PEN para la fecha de la solicitud y podrÃ¡s ver la simulaciÃ³n.",
  "Original request Â· PEN": "Solicitud original Â· PEN",
  "Scenario Â· PEN": "Escenario Â· PEN",
  "Scenario spend": "Gasto del escenario", "Remaining": "Disponible", "Shortfall": "DÃ©ficit",
  "Available now": "Disponible ahora", "Budget shortfall": "DÃ©ficit presupuestal",
  "Remaining after scenario": "Disponible despuÃ©s del escenario",
  "Remaining with original request": "Disponible con la solicitud original",
  "Annual budget": "Presupuesto anual", "Monthly budget": "Presupuesto mensual",
  "Available budget": "Presupuesto disponible",
  "Informational budget only. This balance is not an enforced spending limit.": "Presupuesto informativo. Este saldo no constituye un lÃ­mite obligatorio de gasto.",
  "Annual-only plan: no separate monthly limit.": "Plan anual: no tiene un lÃ­mite mensual independiente.",
  "Advances commit their expense budget at rendition. This is a planning estimate, not a commitment on approval.": "Las entregas a rendir comprometen el presupuesto de gasto en la rendiciÃ³n. Esta es una estimaciÃ³n de planificaciÃ³n, no un compromiso al aprobar.",
  "Availability is checked again when the request reaches budget commitment.": "La disponibilidad se vuelve a validar al registrar el compromiso presupuestal.",
  "All balances are in PEN, using the recorded exchange rate for the request date.": "Todos los saldos estÃ¡n en PEN, con el tipo de cambio registrado para la fecha de la solicitud.",
  "Calculated at": "Calculado a las"
};
