// Spanish copy for UI strings that previously fell back to English.
export default {
  "8 digits": "8 dígitos",
  "A signed CCI letter is mandatory before the CXP returns to the payment queue.": "Se requiere una carta CCI firmada antes de que la CXP vuelva a la cola de pagos.",
  "A1 and A2 vouchers, batch outcomes and isolated observations are independently traceable.": "Los comprobantes A1 y A2, los resultados de lote y las observaciones aisladas se rastrean por separado.",
  "A2 Batch Invoices": "Comprobantes por lote A2",
  "Access": "Acceso",
  "Accounting / Treasury": "Contabilidad / Tesorería",
  "Accounting line": "Línea contable",
  "Accounting reviews only invoices isolated by SUNAT, document, duplicate, or PO-ceiling controls. Valid invoices from the same batch remain provisioned.": "Contabilidad revisa solo los comprobantes aislados por controles SUNAT, documentales, de duplicidad o de tope de OC. Los comprobantes válidos del mismo lote siguen provisionados.",
  "Accounts payable record": "Registro de cuentas por pagar",
  "Accounts Payable records": "Registros de cuentas por pagar",
  "Active requests": "Solicitudes activas",
  "Active requests from your team": "Solicitudes activas de tu equipo",
  "Add...": "Agregar...",
  "Additional permissions": "Permisos adicionales",
  "All banks": "Todos los bancos",
  "All expense natures": "Todas las naturalezas de gasto",
  "All export statuses": "Todos los estados de exportación",
  "All rendition statuses": "Todos los estados de rendición",
  "All sources": "Todas las fuentes",
  "Annul this request?": "¿Anular esta solicitud?",
  "Any unexecuted reservation is released idempotently and the action is audited.": "Toda reserva no ejecutada se libera sin duplicarse y la acción queda auditada.",
  "Applicable USD selling rate": "Tipo de cambio venta USD aplicable",
  "Approval areas": "Áreas de aprobación",
  "Approve and forward this request?": "¿Aprobar y derivar esta solicitud?",
  "Approve budget exception?": "¿Aprobar la excepción presupuestal?",
  "Approve exception": "Aprobar excepción",
  "Approve requests": "Aprobar solicitudes",
  "Approve this request and finalize?": "¿Aprobar y finalizar esta solicitud?",
  "Area / School": "Área / Escuela",
  "Area, or * for all": "Área, o * para todas",
  "Asset category": "Categoría del activo",
  "Authorized CeCos": "CeCos autorizados",
  "Authorized Cost Centers": "Centros de costos autorizados",
  "Batch": "Lote",
  "BBVA certification": "Certificación BBVA",
  "Behavior": "Comportamiento",
  "Bounce": "Rebote",
  "Budget exception": "Excepción presupuestal",
  "Budget, PO ceiling, SUNAT and duplicate controls": "Controles de presupuesto, tope de OC, SUNAT y duplicidad",
  "Cancel unpaid CXP": "Anular CXP no pagada",
  "CAPEX / OPEX is not selected when the advance is created. The final expense is recognized when Accounting validates the rendition.": "CAPEX / OPEX no se elige al crear el adelanto. El gasto final se reconoce cuando Contabilidad valida la rendición.",
  "Certification is a separate, audited action from editing the format. Mark a format certified only after Treasury/BBVA formally accepts the generated PEN/USD test files. Files already generated keep the certification state that applied when they were created.": "La certificación es una acción auditada, separada de la edición del formato. Certifica un formato solo cuando Tesorería/BBVA acepte formalmente los archivos de prueba PEN/USD. Los archivos ya generados conservan el estado de certificación vigente al crearse.",
  "Certified at": "Certificado el",
  "Certified by": "Certificado por",
  "Certify": "Certificar",
  "Certify bank formats": "Certificar formatos bancarios",
  "Checking SUNAT legal representatives...": "Consultando representantes legales en SUNAT...",
  "Clear": "Limpiar",
  "Close this request?": "¿Cerrar esta solicitud?",
  "Commit this request budget?": "¿Comprometer el presupuesto de esta solicitud?",
  "Configuration": "Configuración",
  "Configure BBVA PEN and USD formats using Treasury-confirmed field values. Existing bank files retain their original format. Certification is managed separately below.": "Configura los formatos BBVA en PEN y USD con los valores confirmados por Tesorería. Los archivos existentes conservan su formato original. La certificación se gestiona abajo.",
  "Confirm actual bank payment": "Confirmar el pago bancario real",
  "Confirm the item or report the bank rejection. A rejected item becomes PAGO_REBOTADO without cancelling other invoices in the same request.": "Confirma el ítem o reporta el rechazo bancario. Un ítem rechazado pasa a PAGO_REBOTADO sin anular otros comprobantes de la misma solicitud.",
  "Confirmation posts the payment journal and does not infer payment from a downloaded TXT. Enter less than the outstanding amount to record a partial payment; the remaining balance stays open for a later confirmation.": "La confirmación registra el asiento de pago; descargar el TXT no implica pago. Ingresa un monto menor al pendiente para un pago parcial; el saldo queda abierto para una confirmación posterior.",
  "Conformity evidence": "Evidencia de conformidad",
  "Cost centers": "Centros de costos",
  "Create purchase orders": "Crear órdenes de compra",
  "Create requests": "Crear solicitudes",
  "Current selection": "Selección actual",
  "CXP provision and bank payment processing": "Provisión de CXP y procesamiento del pago bancario",
  "Deactivate profile": "Desactivar perfil",
  "Deactivate this employee bank profile?": "¿Desactivar este perfil bancario del colaborador?",
  "Deductible": "Deducible",
  "Default Cost Center": "Centro de costos predeterminado",
  "Defined at rendition validation": "Se define al validar la rendición",
  "Delete request": "Eliminar solicitud",
  "Details": "Detalles",
  "Dimensions": "Dimensiones",
  "Direct CAPEX purchase": "Compra CAPEX directa",
  "Direct reports": "Reportes directos",
  "Document": "Documento",
  "Domicile condition": "Condición de domicilio",
  "Effective From": "Vigente desde",
  "Employee": "Colaborador",
  "Employee code": "Código de colaborador",
  "Employee DNI": "DNI del colaborador",
  "Enter supplier RUC": "Ingresa el RUC del proveedor",
  "entry types": "tipos de asiento",
  "Escalate above amount (PEN)": "Escalar por encima de (PEN)",
  "Escalated approver role": "Rol aprobador escalado",
  "Exception approver": "Aprobador de la excepción",
  "Exception approver role": "Rol aprobador de la excepción",
  "Existing order": "Orden existente",
  "Expected benefit": "Beneficio esperado",
  "expense natures": "naturalezas de gasto",
  "Expense type": "Tipo de gasto",
  "export status": "estado de exportación",
  "Fallback used": "Se usó respaldo",
  "Finance Configurations": "Parámetros financieros",
  "From": "Desde",
  "Generate bank files": "Generar archivos bancarios",
  "Generate this bank TXT instruction?": "¿Generar esta instrucción bancaria TXT?",
  "Homologate suppliers": "Homologar proveedores",
  "How exceeding this value is treated where it's checked - not every key enforces every behavior.": "Cómo se trata superar este valor donde se verifica; no todas las claves aplican todos los comportamientos.",
  "Identity": "Identificación",
  "Individual": "Individual",
  "Investment classification and financial evaluation captured in the official request.": "Clasificación de la inversión y evaluación financiera registradas en la solicitud oficial.",
  "Invoice control register": "Registro de control de comprobantes",
  "Invoice date": "Fecha del comprobante",
  "Invoice observations": "Observaciones de comprobantes",
  "Invoice Observations": "Observaciones de comprobantes",
  "Journal lines": "Líneas del asiento",
  "Key": "Clave",
  "Leave blank for no amount limit within this area/expense-nature match.": "Déjalo vacío para no limitar el monto en esta área y naturaleza de gasto.",
  "Loading...": "Cargando...",
  "Make this account preferred?": "¿Marcar esta cuenta como preferida?",
  "Manage budget": "Gestionar presupuesto",
  "Manage master data": "Gestionar datos maestros",
  "Manage own bank account": "Gestionar cuenta bancaria propia",
  "Manage users": "Gestionar usuarios",
  "Mass upload batches": "Lotes de carga masiva",
  "Match all confirmed CXP payments to the bank statement before Accounting closure.": "Concilia todos los pagos de CXP confirmados con el extracto bancario antes del cierre contable.",
  "Max amount": "Monto máximo",
  "Max amount (PEN)": "Monto máximo (PEN)",
  "Min. 10 characters. Not saved in drafts.": "Mínimo 10 caracteres. No se guarda en borradores.",
  "My Team": "Mi equipo",
  "New payment files use BBVA. Beneficiary accounts may use another bank through CCI.": "Los archivos de pago nuevos usan BBVA. Las cuentas beneficiarias pueden ser de otro banco mediante CCI.",
  "No action available": "No hay acciones disponibles",
  "No additional CeCos": "Sin CeCos adicionales",
  "No DNI linked": "Sin DNI vinculado",
  "Non-deductible amounts remain charged to the collaborator until reimbursement or payroll deduction is recorded.": "Los montos no deducibles siguen a cargo del colaborador hasta registrar su devolución o descuento por planilla.",
  "Not ready": "No listo",
  "Numeric thresholds that change financial behavior (mobility daily limit, unsupported-expense limit, rendition overdue window, supplier homologation validity). Every change is audited.": "Umbrales numéricos que cambian el comportamiento financiero (límite diario de movilidad, gasto sin sustento, plazo de rendición, vigencia de homologación). Cada cambio queda auditado.",
  "Observation": "Observación",
  "Observe profile": "Observar perfil",
  "Observe request": "Observar solicitud",
  "Observe this employee bank profile?": "¿Observar este perfil bancario del colaborador?",
  "Observe this request?": "¿Observar esta solicitud?",
  "Official / authoritative": "Oficial / autoritativo",
  "Official SUNAT": "SUNAT oficial",
  "Only a permitted draft or rejected record can be deleted. This cannot be undone.": "Solo se puede eliminar un borrador o registro rechazado permitido. No se puede deshacer.",
  "Only a reconciled request in an open permitted period can be closed.": "Solo se puede cerrar una solicitud conciliada en un período abierto permitido.",
  "Only draft requests can be deleted. This action cannot be undone.": "Solo se pueden eliminar solicitudes en borrador. Esta acción no se puede deshacer.",
  "Only Management/Rectorate authority may decide a budget exception - Admin cannot approve on Management's behalf.": "Solo Gerencia/Rectorado puede decidir una excepción presupuestal; Admin no puede aprobar en su nombre.",
  "Open a batch to inspect per-invoice results.": "Abre un lote para revisar el resultado de cada comprobante.",
  "Open request": "Abrir solicitud",
  "Opened": "Abierta",
  "Opened by": "Abierta por",
  "Operating expense frequency and controlled recurrence.": "Frecuencia del gasto operativo y recurrencia controlada.",
  "Operation": "Operación",
  "Operational track": "Vía operativa",
  "Optional comma-separated canonical expense natures.": "Naturalezas de gasto opcionales, separadas por comas.",
  "Optional comma-separated canonical request types.": "Tipos de solicitud opcionales, separados por comas.",
  "Optional. Above this requested amount, a different (higher) authority is required instead.": "Opcional. Por encima de este monto se requiere una autoridad superior.",
  "Order readiness": "Preparación de la orden",
  "Organization": "Organización",
  "Organizational unit": "Unidad orgánica",
  "Organizational unit code": "Código de unidad orgánica",
  "Outstanding advances requiring evidence or Accounting validation. Rendition remains separate from payment status.": "Adelantos pendientes de sustento o validación contable. La rendición se muestra aparte del estado de pago.",
  "Paid amount": "Monto pagado",
  "Paid at": "Pagado el",
  "Paid date": "Fecha de pago",
  "Paid invoices": "Comprobantes pagados",
  "Payback": "Recuperación",
  "Payback period": "Periodo de recuperación",
  "Payment batches": "Lotes de pago",
  "Payment bounce": "Rebote de pago",
  "Payment confirmations": "Confirmaciones de pago",
  "Payment reconciliation": "Conciliación de pagos",
  "Payment reprogram": "Reprogramación de pago",
  "Payment status": "Estado del pago",
  "Pending / submitted / observed": "Pendiente / enviada / observada",
  "Pending rendition requirements": "Requisitos de rendición pendientes",
  "People who report to you, directly, and the requests they have submitted.": "Personas que te reportan directamente y las solicitudes que han enviado.",
  "Permitted expense natures": "Naturalezas de gasto permitidas",
  "Permitted request types": "Tipos de solicitud permitidos",
  "PO remaining balance": "Saldo restante de la OC",
  "Process accounting": "Procesar contabilidad",
  "Projected balance": "Saldo proyectado",
  "Propose suppliers": "Proponer proveedores",
  "Provider mode": "Modo del proveedor",
  "Qty": "Cant.",
  "Rate date": "Fecha del tipo de cambio",
  "RCO-FOR-002 onboarding, SUNAT validations, protected evidence, Finance review, banking history and controlled PRV assignment.": "Alta RCO-FOR-002, validaciones SUNAT, evidencia protegida, revisión de Finanzas, historial bancario y asignación controlada de PRV.",
  "Ready": "Listo",
  "Reason": "Motivo",
  "Reason for cancelling this unpaid CXP (required):": "Motivo para anular esta CXP no pagada (obligatorio):",
  "Reconcile bank payment": "Conciliar pago bancario",
  "Reconcile payment": "Conciliar pago",
  "Reconcile payments": "Conciliar pagos",
  "Reconciled invoices": "Comprobantes conciliados",
  "Reconciliation difference": "Diferencia de conciliación",
  "Record an authenticated electronic sign-off and advance the configured route.": "Registra una conformidad electrónica autenticada y avanza la ruta configurada.",
  "Record your approval as final. No further manager will review it — the request moves directly into the budget/accounting pipeline.": "Registra tu aprobación como final. Ningún otro jefe la revisará: la solicitud pasa directamente a presupuesto y contabilidad.",
  "Record your recommendation for Management. This does not authorize an overrun.": "Registra tu recomendación para Gerencia. Esto no autoriza un sobregiro.",
  "Recurring commitment": "Compromiso recurrente",
  "Reference — not authoritative": "Referencial, no autoritativo",
  "Reference / comment": "Referencia / comentario",
  "Register A1 invoice and conformity": "Registrar comprobante A1 y conformidad",
  "Reject budget exception?": "¿Rechazar la excepción presupuestal?",
  "Reject exception": "Rechazar excepción",
  "Reject it and preserve the complete decision record.": "Recházala conservando el registro completo de la decisión.",
  "Reject profile": "Rechazar perfil",
  "Reject the Finance review and preserve a distinct audited result.": "Rechaza la revisión de Finanzas conservando un resultado auditado.",
  "Reject the request and preserve the full decision trail. A reason is mandatory.": "Rechaza la solicitud conservando el historial de decisiones. El motivo es obligatorio.",
  "Reject this employee bank profile?": "¿Rechazar este perfil bancario del colaborador?",
  "Remaining PO balance": "Saldo restante de la OC",
  "Remove": "Quitar",
  "Remove certification": "Quitar certificación",
  "Rendition status": "Estado de la rendición",
  "rendition statuses": "estados de rendición",
  "Renewal date": "Fecha de renovación",
  "Reported": "Reportado",
  "Reports": "Reportes",
  "Reprocess payments": "Reprocesar pagos",
  "Reprogram bounced payment": "Reprogramar pago rebotado",
  "Request lifecycle": "Ciclo de la solicitud",
  "Request status": "Estado de la solicitud",
  "Requested date": "Fecha solicitada",
  "Requester": "Solicitante",
  "Requests from your team": "Solicitudes de tu equipo",
  "Required only when an escalation amount is set. Same Management-only restriction applies.": "Obligatorio solo si hay monto de escalamiento. Aplica la misma restricción a Gerencia.",
  "Required to certify": "Obligatorio para certificar",
  "Requirement, CECO, three quotations and conformity": "Requerimiento, CECO, tres cotizaciones y conformidad",
  "Resolution": "Resolución",
  "Retrieved": "Obtenido",
  "Retry": "Reintentar",
  "Retry budget commitment": "Reintentar compromiso presupuestal",
  "Retry budget commitment?": "¿Reintentar el compromiso presupuestal?",
  "Return it for documented corrections without erasing history.": "Devuélvela para correcciones documentadas sin borrar el historial.",
  "Return it to its owner with a mandatory explanation.": "Devuélvela a su responsable con una explicación obligatoria.",
  "Return request": "Devolver solicitud",
  "Return the banking facts for correction with mandatory Finance comments.": "Devuelve los datos bancarios para corrección con comentarios obligatorios de Finanzas.",
  "Return the official details for correction while preserving the RG and history.": "Devuelve los datos oficiales para corrección conservando el RG y el historial.",
  "Return the request to its owner without erasing the approval history.": "Devuelve la solicitud a su responsable sin borrar el historial de aprobación.",
  "Return this request?": "¿Devolver esta solicitud?",
  "Revalidate observed invoice": "Revalidar comprobante observado",
  "Review batch invoices": "Revisar comprobantes por lote",
  "Review budget exception": "Revisar excepción presupuestal",
  "Review employee bank accounts": "Revisar cuentas bancarias de colaboradores",
  "Review every invoice-level CXP independently, including A2 batch origin, Purchase Order balance, SUNAT result, payment priority, and bounced-payment status.": "Revisa cada CXP por comprobante: origen del lote A2, saldo de la OC, resultado SUNAT, prioridad de pago y rebotes.",
  "Review renditions": "Revisar rendiciones",
  "Role / title": "Rol / cargo",
  "RUC not found in the current SUNAT Padrón": "RUC no encontrado en el Padrón SUNAT vigente",
  "Schedule payments": "Programar pagos",
  "School": "Escuela",
  "Search accounting period...": "Buscar período contable...",
  "Search authorized CECO...": "Buscar CECO autorizado...",
  "Search batch...": "Buscar lote...",
  "Search Cost Center, account, project, or period...": "Buscar centro de costos, cuenta, proyecto o período...",
  "Search entry, request, account, or description...": "Buscar asiento, solicitud, cuenta o descripción...",
  "Search name or RUC/DNI...": "Buscar nombre o RUC/DNI...",
  "Search now": "Buscar ahora",
  "Search request or period...": "Buscar solicitud o período...",
  "Search request, supplier, or document...": "Buscar solicitud, proveedor o documento...",
  "Search request, supplier, or requester...": "Buscar solicitud, proveedor o solicitante...",
  "Search request, supplier, voucher, or cost center...": "Buscar solicitud, proveedor, comprobante o centro de costos...",
  "Search request, supplier, voucher, Purchase Order, or bank batch...": "Buscar solicitud, proveedor, comprobante, OC o lote bancario...",
  "Search RUC, voucher or observation...": "Buscar RUC, comprobante u observación...",
  "Search supplier, RUC, voucher, request, or CXP...": "Buscar proveedor, RUC, comprobante, solicitud o CXP...",
  "Select active or transitional control, the insufficient-budget exception strategy, and who may authorize an extraordinary exception, by dimension.": "Define por dimensión el control activo o transitorio, la estrategia ante presupuesto insuficiente y quién autoriza una excepción extraordinaria.",
  "Select an active Purchase Order and upload a ZIP of XML/PDF pairs or an Excel invoice template. Every voucher is validated independently.": "Selecciona una OC activa y sube un ZIP con pares XML/PDF o una plantilla Excel. Cada comprobante se valida por separado.",
  "Selected CXP": "CXP seleccionada",
  "Selecting a role fills the corresponding UMA demo DNI and password.": "Al elegir un rol se completan el DNI y la contraseña demo correspondientes.",
  "Service period": "Periodo del servicio",
  "Source / reference": "Fuente / referencia",
  "Source code": "Código de origen",
  "Source description": "Descripción de origen",
  "Source: SUNAT Consulta RUC public portal. This is additional validation and does not replace the supplier's supporting legal documentation.": "Fuente: portal público Consulta RUC de SUNAT. Es una validación adicional y no reemplaza la documentación legal del proveedor.",
  "Strategy": "Estrategia",
  "Successful": "Exitosos",
  "SUNAT Consulta RUC could not be reached.": "No se pudo conectar con Consulta RUC de SUNAT.",
  "SUNAT Consulta RUC did not return legal representatives for this RUC.": "Consulta RUC de SUNAT no devolvió representantes legales para este RUC.",
  "SUNAT Legal Representatives": "Representantes legales en SUNAT",
  "SUNAT Padrón data loaded automatically": "Datos del Padrón SUNAT cargados automáticamente",
  "SUNAT reports multiple representatives. Select the person UMA wants to record as the primary representative; the system will not guess automatically.": "SUNAT reporta varios representantes. Elige a quién registrar como representante principal; el sistema no lo decide por ti.",
  "SUNAT representative lookup temporarily unavailable": "Consulta de representantes SUNAT no disponible por ahora",
  "SUNAT vouchers": "Comprobantes SUNAT",
  "SUNAT, duplicate identity, and remaining PO ceiling are checked per invoice. Invalid invoices are isolated instead of stopping the entire batch.": "SUNAT, duplicidad y tope restante de la OC se validan por comprobante. Los inválidos se aíslan sin detener el lote.",
  "Supplier bank review": "Revisión bancaria del proveedor",
  "Supplier Finance review": "Revisión de Finanzas del proveedor",
  "Supplier taxpayer review": "Revisión tributaria del proveedor",
  "Team members": "Miembros del equipo",
  "Technical detail": "Detalle técnico",
  "Technical justification": "Justificación técnica",
  "Terminal states": "Estados finales",
  "The backend will re-check current dimensional availability and the approved exception strategy.": "El sistema volverá a verificar la disponibilidad por dimensión y la estrategia de excepción aprobada.",
  "The backend will validate every budget dimension and exception rule before reserving funds.": "El sistema validará cada dimensión presupuestal y regla de excepción antes de reservar fondos.",
  "The bank rejected this transfer. A signed CCI letter is required before reprogramming.": "El banco rechazó esta transferencia. Se requiere una carta CCI firmada antes de reprogramar.",
  "The operational track defines how the transaction is processed; CAPEX / OPEX defines the economic classification of the spend.": "La vía operativa define cómo se procesa la transacción; CAPEX / OPEX define la clasificación económica del gasto.",
  "The Padrón validation above remains valid and supplier creation can continue.": "La validación del Padrón sigue vigente y puedes continuar con el alta del proveedor.",
  "The previous payment destination remains auditable; the replacement evidence is stored before reopening the CXP.": "El destino de pago anterior sigue auditable; la nueva evidencia se guarda antes de reabrir la CXP.",
  "The previous preferred account remains in history and is no longer selected for new reimbursements.": "La cuenta preferida anterior queda en el historial y ya no se usa para nuevos reembolsos.",
  "The profile remains in history and cannot remain preferred.": "El perfil queda en el historial y deja de ser preferido.",
  "The profile stays in history and cannot be used for reimbursement.": "El perfil queda en el historial y no se puede usar para reembolsos.",
  "The request will remain blocked from budget commitment.": "La solicitud seguirá bloqueada para compromiso presupuestal.",
  "The requester must correct the stated observations before resubmission.": "El solicitante debe corregir las observaciones antes de reenviar.",
  "The server validates SUNAT, anti-duplication and the PO ceiling before creating CXP.": "El sistema valida SUNAT, duplicidad y el tope de la OC antes de crear la CXP.",
  "The single SUNAT representative was automatically copied into the Legal Representative fields below.": "El único representante SUNAT se copió automáticamente en los campos de representante legal.",
  "The supplier comparison and recommendation remain linked to uploaded evidence.": "La comparación y recomendación de proveedores siguen vinculadas a la evidencia cargada.",
  "The supplier form is already available while Consulta RUC is checked in the background.": "El formulario del proveedor ya está disponible mientras se consulta el RUC en segundo plano.",
  "This assigns one immutable PRV code, activates the supplier, and makes it available to the existing request workflow.": "Esto asigna un código PRV inmutable, activa al proveedor y lo habilita para las solicitudes.",
  "This records an audited exception decision. A budget-increase strategy still requires sufficient allocation before commitment.": "Esto registra una decisión de excepción auditada. Una estrategia de ampliación aún requiere asignación suficiente antes del compromiso.",
  "This records an authorized manual UMA Finance review. It is not external bank verification.": "Esto registra una revisión manual autorizada de Finanzas UMA. No es una verificación bancaria externa.",
  "This records your approval and sends it to the next manager in the chain for a further decision.": "Esto registra tu aprobación y la envía al siguiente jefe de la cadena para su decisión.",
  "This records your approval as final. No further manager will review it — the request moves directly into the budget/accounting pipeline.": "Esto registra tu aprobación como final. Ningún otro jefe la revisará: la solicitud pasa directamente a presupuesto y contabilidad.",
  "This settles the selected Accounts Payable record": "Esto liquida el registro de cuentas por pagar seleccionado",
  "Title": "Título",
  "To": "Hasta",
  "Track B (direct payment) shortens the normal A1 procurement path - it is only available where a matching active rule exists for the request's area, expense nature, and amount. No matching rule means Track B is refused at submission.": "La Vía B (pago directo) acorta el flujo A1 y solo aplica si existe una regla activa para el área, la naturaleza del gasto y el monto. Sin regla, la Vía B se rechaza al enviar.",
  "Track B Eligibility": "Elegibilidad Vía B",
  "Track B has no prior Purchase Order. Provide a clear business justification and the required supporting evidence for this capital expenditure.": "La Vía B no tiene OC previa. Incluye una justificación clara y la evidencia requerida para este gasto de capital.",
  "Track C - Advance to render": "Vía C - Entrega a rendir",
  "Track C rendition is shown separately from payment status.": "La rendición de la Vía C se muestra aparte del estado de pago.",
  "Type and press Enter": "Escribe y presiona Enter",
  "UMA Cost Centers with their area, organizational hierarchy, import source, and budget controls.": "Centros de costos UMA con su área, jerarquía, origen de importación y controles presupuestales.",
  "UMA source bank": "Banco de origen UMA",
  "Updating balances…": "Actualizando saldos…",
  "Upload batch invoices": "Subir comprobantes por lote",
  "Upload the documents required for invoice registration and Accounting. Amount fields are immutable and read from XML.": "Sube los documentos requeridos para el registro del comprobante y Contabilidad. Los montos se leen del XML y no se editan.",
  "Use as legal representative": "Usar como representante legal",
  "Use MANUAL unless a configured provider supplied the rate.": "Usa MANUAL salvo que un proveedor configurado haya dado el tipo de cambio.",
  "Useful life": "Vida útil",
  "User Administration": "Administración de usuarios",
  "Users, roles and access.": "Usuarios, roles y accesos.",
  "Validation": "Validación",
  "Verify profile": "Verificar perfil",
  "Verify this employee bank profile?": "¿Verificar este perfil bancario del colaborador?",
  "View all requests": "Ver todas las solicitudes",
  "View audit": "Ver auditoría",
  "View batch": "Ver lote",
  "View budget": "Ver presupuesto",
  "View CXP details": "Ver detalle de la CXP",
  "View management portal": "Ver portal gerencial",
  "View payment bank data": "Ver datos bancarios de pago",
  "View reports": "Ver reportes",
  "View supplier bank data": "Ver datos bancarios del proveedor",
  "Void requests": "Anular solicitudes",
  "When 11 digits are entered, UMA automatically checks the Supplier Master, SUNAT Padrón and SUNAT legal representatives.": "Al ingresar 11 dígitos, UMA consulta automáticamente el maestro de proveedores, el Padrón SUNAT y los representantes legales.",
  "XML amount": "Monto XML",
  "You can continue entering the proposal manually, but SUNAT validation will still be required before homologation.": "Puedes seguir registrando la propuesta manualmente, pero se requerirá la validación SUNAT antes de homologar.",
  "YYYY or YYYY-MM": "AAAA o AAAA-MM",
  "Approved requests awaiting a Purchase Order": "Solicitudes aprobadas sin orden de compra",
  "Approved, awaiting PO": "Aprobadas, pendientes de OC",
  "Blocked controls (30d)": "Controles bloqueados (30 d)",
  "Budget exceptions pending": "Excepciones presupuestales pendientes",
  "CXP ready for Treasury": "CXP listas para Tesorería",
  "Controlled spend": "Gasto controlado",
  "In active workflow": "En flujo activo",
  "Invoices received against POs": "Comprobantes recibidos contra OC",
  "Missing exchange-rate dates": "Fechas sin tipo de cambio",
  "Oldest approval": "Aprobación más antigua",
  "Open Purchase Orders": "Órdenes de compra abiertas",
  "Payments awaiting confirmation": "Pagos por confirmar",
  "Pending commitments": "Compromisos pendientes",
  "Pending period items": "Pendientes del período",
  "Renditions outstanding": "Rendiciones pendientes",
  "Requests awaiting approval": "Solicitudes por aprobar",
  "Requests awaiting fiscal processing": "Solicitudes por procesar fiscalmente",
  "Returned / observed": "Devueltas / observadas",
  "SLA overdue": "SLA vencido",
  "Supplier validations": "Validaciones de proveedores",
  "Suppliers awaiting homologation": "Proveedores por homologar",
  "Applies to": "Aplica a",
  "Exception authority": "Autoridad de excepción",
  "Field configuration": "Configuración de campos",
  "Format": "Formato",
  "Rule": "Regla",
  "Timing": "Plazos",
  "Validity": "Vigencia",
  "Where it can be used": "Dónde se puede usar",
  "Approval": "Aprobación",
  "OPEX - Operating expenditure": "OPEX - Gasto operativo",
  "CAPEX - Capital expenditure": "CAPEX - Gasto de capital",
  "A1 - Formal purchase with PO": "A1 - Compra formal con OC",
  "A2 - Batch invoices against PO": "A2 - Comprobantes por lote contra OC",
  "B - Direct invoice / advance payment": "B - Comprobante directo / pago anticipado",
  "C - Advance to render / petty cash": "C - Entrega a rendir / caja chica",
  "Area Director": "Director de área",
  "Vice Rector": "Vicerrector",
  "Rectorate": "Rectorado",
  "General management": "Gerencia general",
  "Management viewer": "Visor de gerencia",
  "Budget": "Presupuesto",
  "Status": "Estado"
};
