export const ROLES = Object.freeze({
  ADMIN: "Admin",
  SOLICITOR: "Solicitor",
  APPROVER: "Approver",
  ACCOUNTING: "Accounting",
  TREASURY: "Treasury",
  BUDGET: "Budget",
  PROCUREMENT: "Procurement",
  MANAGEMENT: "Management",
  MANAGEMENT_VIEWER: "ManagementViewer"
});

export const PERMISSIONS = Object.freeze({
  REQUEST_CREATE: "request:create",
  REQUEST_VIEW_ALL: "request:view-all",
  REQUEST_APPROVE: "request:approve",
  REQUEST_VOID: "request:void",
  SUPPLIER_PROPOSE: "supplier:propose",
  SUPPLIER_HOMOLOGATE: "supplier:homologate",
  SUPPLIER_BANK_VIEW: "supplier:bank-view",
  BUDGET_VIEW: "budget:view",
  BUDGET_MANAGE: "budget:manage",
  ACCOUNTING_PROCESS: "accounting:process",
  PERIOD_MANAGE: "period:manage",
  TREASURY_SCHEDULE: "treasury:schedule",
  TREASURY_FILE: "treasury:file",
  PAYMENT_CONFIRM: "payment:confirm",
  RECONCILE: "payment:reconcile",
  REPORT_VIEW: "report:view",
  MANAGEMENT_PORTAL_VIEW: "management-portal:view",
  AUDIT_VIEW: "audit:view",
  MASTER_DATA_MANAGE: "master-data:manage",
  USER_MANAGE: "user:manage",
  EMPLOYEE_BANK_MANAGE_OWN: "employee-bank:manage-own",
  EMPLOYEE_BANK_REVIEW: "employee-bank:review",
  EMPLOYEE_BANK_VIEW_PAYMENT: "employee-bank:view-payment",
  RENDITION_REVIEW: "rendition:review",
  PROCUREMENT_ORDER_CREATE: "procurement-order:create",
  BATCH_INVOICE_UPLOAD: "batch-invoice:upload",
  BATCH_INVOICE_REVIEW: "batch-invoice:review",
  PAYMENT_REPROCESS: "payment:reprocess"
});

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.SOLICITOR]: [PERMISSIONS.REQUEST_CREATE, PERMISSIONS.SUPPLIER_PROPOSE, PERMISSIONS.EMPLOYEE_BANK_MANAGE_OWN, PERMISSIONS.BATCH_INVOICE_UPLOAD],
  [ROLES.APPROVER]: [PERMISSIONS.REQUEST_VIEW_ALL, PERMISSIONS.REQUEST_APPROVE, PERMISSIONS.BUDGET_VIEW, PERMISSIONS.REPORT_VIEW],
  [ROLES.ACCOUNTING]: [
    PERMISSIONS.REQUEST_VIEW_ALL,
    PERMISSIONS.SUPPLIER_HOMOLOGATE,
    PERMISSIONS.SUPPLIER_BANK_VIEW,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.ACCOUNTING_PROCESS,
    PERMISSIONS.PERIOD_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.MASTER_DATA_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.EMPLOYEE_BANK_REVIEW,
    PERMISSIONS.EMPLOYEE_BANK_VIEW_PAYMENT,
    PERMISSIONS.RENDITION_REVIEW,
    PERMISSIONS.BATCH_INVOICE_UPLOAD,
    PERMISSIONS.BATCH_INVOICE_REVIEW
  ],
  [ROLES.TREASURY]: [
    PERMISSIONS.REQUEST_VIEW_ALL,
    PERMISSIONS.SUPPLIER_BANK_VIEW,
    PERMISSIONS.TREASURY_SCHEDULE,
    PERMISSIONS.TREASURY_FILE,
    PERMISSIONS.PAYMENT_CONFIRM,
    PERMISSIONS.RECONCILE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.EMPLOYEE_BANK_VIEW_PAYMENT,
    PERMISSIONS.PAYMENT_REPROCESS
  ],
  // Budget validates/commits/reserves funds and prepares exceptions; it no longer issues
  // Purchase Orders directly — that is Procurement's ownership (see ROLES.PROCUREMENT).
  [ROLES.BUDGET]: [PERMISSIONS.REQUEST_VIEW_ALL, PERMISSIONS.BUDGET_VIEW, PERMISSIONS.BUDGET_MANAGE, PERMISSIONS.REPORT_VIEW],
  [ROLES.PROCUREMENT]: [PERMISSIONS.REQUEST_VIEW_ALL, PERMISSIONS.SUPPLIER_BANK_VIEW, PERMISSIONS.PROCUREMENT_ORDER_CREATE, PERMISSIONS.REPORT_VIEW],
  [ROLES.MANAGEMENT]: [PERMISSIONS.REQUEST_VIEW_ALL, PERMISSIONS.REQUEST_APPROVE, PERMISSIONS.BUDGET_VIEW, PERMISSIONS.REPORT_VIEW, PERMISSIONS.MANAGEMENT_PORTAL_VIEW],
  [ROLES.MANAGEMENT_VIEWER]: [PERMISSIONS.MANAGEMENT_PORTAL_VIEW]
});

export const REQUEST_TYPE = Object.freeze({
  OPEX: "OPEX",
  CAPEX: "CAPEX",
  ENTREGA_RENDIR: "ENTREGA_RENDIR",
  REEMBOLSO_CON_SUSTENTO: "REEMBOLSO_CON_SUSTENTO",
  REEMBOLSO_SIN_SUSTENTO: "REEMBOLSO_SIN_SUSTENTO",
  PAGO_CON_COTIZACION: "PAGO_CON_COTIZACION"
});

export const REQUEST_TYPES = Object.freeze(Object.values(REQUEST_TYPE));

export const FLOW_TYPE = Object.freeze({
  A1: "A1",
  A2: "A2",
  B: "B",
  C: "C"
});

export const FLOW_TYPES = Object.freeze(Object.values(FLOW_TYPE));

export const DOCUMENT_PHASE = Object.freeze({
  SUBMISSION: "SUBMISSION",
  PROCUREMENT: "PROCUREMENT",
  INVOICE_REGISTRATION: "INVOICE_REGISTRATION",
  ACCOUNTING: "ACCOUNTING",
  RENDITION: "RENDITION"
});

export const DOCUMENT_PHASES = Object.freeze(Object.values(DOCUMENT_PHASE));

export const EXPENSE_NATURE = Object.freeze({
  GOODS: "GOODS",
  SERVICES: "SERVICES",
  PROFESSIONAL_FEES: "PROFESSIONAL_FEES",
  CONSULTING: "CONSULTING",
  ADVERTISING: "ADVERTISING",
  TRAVEL: "TRAVEL",
  EQUIPMENT: "EQUIPMENT",
  TECHNOLOGY: "TECHNOLOGY",
  INFRASTRUCTURE: "INFRASTRUCTURE",
  LABORATORIES: "LABORATORIES",
  LIBRARY: "LIBRARY",
  RESEARCH: "RESEARCH",
  MAINTENANCE: "MAINTENANCE",
  PETTY_CASH: "PETTY_CASH",
  REIMBURSEMENT_LIQUIDATION: "REIMBURSEMENT_LIQUIDATION"
});

export const EXPENSE_NATURES = Object.freeze(Object.values(EXPENSE_NATURE));
export const REQUEST_PRIORITIES = Object.freeze(["BAJA", "MEDIA", "ALTA"]);

export const APPROVAL_STAGES = Object.freeze({
  AREA_DIRECTOR: "AREA_DIRECTOR",
  VICE_RECTOR: "VICE_RECTOR",
  RECTORATE: "RECTORATE",
  GENERAL_MANAGEMENT: "GENERAL_MANAGEMENT",
  COMPLETE: "COMPLETE"
});

export const APPROVAL_ACTIONS = Object.freeze(["APPROVE", "OBSERVE", "RETURN", "REJECT"]);

export const APPROVAL_ROUTING_MODE = Object.freeze({
  RULE_BASED: "RULE_BASED",
  MANAGER_CHAIN: "MANAGER_CHAIN"
});

export const MAX_APPROVAL_CHAIN_DEPTH = 12;

export const REQUEST_STATUS = Object.freeze({
  DRAFT: "BORRADOR",
  VALIDATION: "EN_VALIDACION",
  SENT: "ENVIADO",
  PENDING_APPROVAL: "PENDIENTE_APROBACION",
  DIRECTOR_APPROVED: "APROBADO_DIRECTOR",
  VICE_RECTOR_APPROVED: "APROBADO_VICERRECTOR",
  APPROVED: "APROBADO",
  BUDGET_COMMITTED: "COMPROMISO_PRESUPUESTAL",
  ACCOUNTED: "CONTABILIZADO",
  PROVISIONED_CXP: "CONTABILIZADO",
  SCHEDULED: "PROGRAMADO",
  BANK_FILE_GENERATED: "TXT_GENERADO",
  PAID: "PAGADO",
  RECONCILED: "CONCILIADO",
  RENDITION_PENDING: "RENDICION_PENDIENTE",
  CLOSED: "CERRADO",
  OBSERVED: "OBSERVADO",
  OBSERVED_BUDGET: "OBSERVADO_PRESUPUESTO",
  OBSERVED_SUNAT: "OBSERVADO_SUNAT",
  OBSERVED_AMOUNT_EXCEEDED: "OBSERVADO_MONTO_EXCEDIDO",
  OBSERVED_BATCH: "OBSERVADO_CARGA_MASIVA",
  PAYMENT_BOUNCED: "PAGO_REBOTADO",
  PAID_CLOSED: "CERRADO",
  RETURNED: "DEVUELTO",
  REJECTED: "RECHAZADO",
  VOIDED: "ANULADO"
});

export const CANONICAL_REQUEST_STATUSES = Object.freeze([...new Set([...Object.values(REQUEST_STATUS), "PAGADO_CERRADO", "PROVISIONADO_CXP"])]);

export const LEGACY_STATUS_MAP = Object.freeze({
  BORRADOR: REQUEST_STATUS.DRAFT,
  PENDIENTE_APROBACION: REQUEST_STATUS.PENDING_APPROVAL,
  APROBADO_DIRECTOR: REQUEST_STATUS.DIRECTOR_APPROVED,
  APROBADO_VICERRECTOR: REQUEST_STATUS.VICE_RECTOR_APPROVED,
  COMPROMISO_PRESUPUESTAL: REQUEST_STATUS.BUDGET_COMMITTED,
  PROVISIONADO_CXP: REQUEST_STATUS.PROVISIONED_CXP,
  PROCESADO_BANCO: REQUEST_STATUS.BANK_FILE_GENERATED,
  PAGADO: REQUEST_STATUS.PAID,
  LIQUIDADO_CERRADO: REQUEST_STATUS.PAID_CLOSED,
  RENDICION_PENDIENTE: REQUEST_STATUS.RENDITION_PENDING,
  ANULADO: REQUEST_STATUS.VOIDED
});

export const LEGACY_REQUEST_TYPE_MAP = Object.freeze({
  OPEX: REQUEST_TYPE.OPEX,
  CAPEX: REQUEST_TYPE.CAPEX,
  "Entrega a Rendir": REQUEST_TYPE.ENTREGA_RENDIR,
  "Reembolso con Sustento": REQUEST_TYPE.REEMBOLSO_CON_SUSTENTO,
  "Reembolso sin Sustento": REQUEST_TYPE.REEMBOLSO_SIN_SUSTENTO,
  "Pago con Cotizacion": REQUEST_TYPE.PAGO_CON_COTIZACION,
  "Pago con Cotización": REQUEST_TYPE.PAGO_CON_COTIZACION
});

export const LEGACY_EXPENSE_NATURE_MAP = Object.freeze({
  "Compra de Bienes": EXPENSE_NATURE.GOODS,
  "Contratacion de Servicios": EXPENSE_NATURE.SERVICES,
  "Contratación de Servicios": EXPENSE_NATURE.SERVICES,
  "Honorarios Profesionales": EXPENSE_NATURE.PROFESSIONAL_FEES,
  Publicidad: EXPENSE_NATURE.ADVERTISING,
  Viajes: EXPENSE_NATURE.TRAVEL,
  Equipamiento: EXPENSE_NATURE.EQUIPMENT,
  Tecnologia: EXPENSE_NATURE.TECHNOLOGY,
  "Tecnología": EXPENSE_NATURE.TECHNOLOGY,
  Infraestructura: EXPENSE_NATURE.INFRASTRUCTURE,
  Laboratorios: EXPENSE_NATURE.LABORATORIES,
  Biblioteca: EXPENSE_NATURE.LIBRARY,
  Investigacion: EXPENSE_NATURE.RESEARCH,
  "Investigación": EXPENSE_NATURE.RESEARCH,
  Mantenimiento: EXPENSE_NATURE.MAINTENANCE,
  "Caja Chica": EXPENSE_NATURE.PETTY_CASH,
  "Reembolso / Liquidacion": EXPENSE_NATURE.REIMBURSEMENT_LIQUIDATION,
  "Reembolso / Liquidación": EXPENSE_NATURE.REIMBURSEMENT_LIQUIDATION
});

export const MANDATORY_XML_TYPES = Object.freeze([
  REQUEST_TYPE.PAGO_CON_COTIZACION,
  REQUEST_TYPE.REEMBOLSO_CON_SUSTENTO
]);

export const DEFAULT_APPROVAL_SLA_HOURS = 24;
export const APPROVAL_SLA_HOURS = Object.freeze({
  [APPROVAL_STAGES.AREA_DIRECTOR]: DEFAULT_APPROVAL_SLA_HOURS,
  [APPROVAL_STAGES.VICE_RECTOR]: DEFAULT_APPROVAL_SLA_HOURS,
  [APPROVAL_STAGES.RECTORATE]: DEFAULT_APPROVAL_SLA_HOURS,
  [APPROVAL_STAGES.GENERAL_MANAGEMENT]: DEFAULT_APPROVAL_SLA_HOURS
});

export const CURRENCY = Object.freeze(["PEN", "USD"]);
export const BANKS = Object.freeze(["BCP", "BBVA", "INTERBANK", "SCOTIABANK"]);
export const SUPPLIER_BANKS = Object.freeze([...BANKS, "BANCO_NACION"]);

export const SUPPLIER_PERSON_TYPES = Object.freeze(["LEGAL_ENTITY", "NATURAL_PERSON_WITH_BUSINESS"]);
export const SUPPLIER_HOMOLOGATION_STATUSES = Object.freeze(["PENDING_VALIDATION", "HOMOLOGATED", "OBSERVED", "REJECTED", "INACTIVE"]);
export const SUPPLIER_OPERATIONAL_STATUSES = Object.freeze(["PENDING_VALIDATION", "ACTIVE", "OBSERVED", "REJECTED", "INACTIVE"]);
export const SUPPLIER_ACCOUNT_TYPES = Object.freeze(["CURRENT", "DETRACTION"]);
export const BANK_ACCOUNT_VERIFICATION_STATUSES = Object.freeze(["PENDING", "VERIFIED", "OBSERVED", "REJECTED", "LEGACY_ACCEPTED"]);
export const BANK_ACCOUNT_OWNERSHIP_RESULTS = Object.freeze(["NOT_REVIEWED", "MATCH", "MISMATCH", "MANUAL_ACCEPTED"]);
export const SUPPLIER_DECLARATION_ANSWERS = Object.freeze(["YES", "NO", "NOT_DECLARED"]);
export const SUPPLIER_REVIEW_RESULTS = Object.freeze(["PENDING", "APPROVED", "OBSERVED", "REJECTED"]);
export const SUPPLIER_PAYMENT_TERM_OPTIONS = Object.freeze(["CREDIT_30", "CREDIT_45", "CUSTOM"]);
export const SUPPLIER_DELIVERY_METHODS = Object.freeze(["CENTRAL_WAREHOUSE", "DESTINATION_SITE", "OTHER"]);
export const PROCUREMENT_ORDER_KINDS = Object.freeze(["PURCHASE", "SERVICE"]);
export const PAYMENT_DESTINATION_SOURCES = Object.freeze(["SUPPLIER", "EMPLOYEE_REIMBURSEMENT"]);
export const BATCH_UPLOAD_STATUSES = Object.freeze(["QUEUED", "PROCESSING", "COMPLETED", "COMPLETED_WITH_OBSERVATIONS", "FAILED"]);
export const VOUCHER_VALIDATION_STATUSES = Object.freeze(["PENDING", "VALID", "OBSERVED_SUNAT", "OBSERVED_DUPLICATE", "OBSERVED_AMOUNT_EXCEEDED", "OBSERVED_BATCH"]);

export const CAPEX_ASSET_CATEGORIES = Object.freeze(["INFRASTRUCTURE", "MACHINERY", "IT_HARDWARE", "SOFTWARE_LICENSES"]);
export const OPEX_EXPENSE_FREQUENCIES = Object.freeze(["ONE_OFF", "MONTHLY_RECURRING", "EVERY_3_MONTHS", "ANNUAL_RENEWAL"]);
export const PAYBACK_UNITS = Object.freeze(["MONTHS", "YEARS"]);
export const RENDITION_LINE_TYPES = Object.freeze(["GOODS", "SERVICES"]);
export const ACKNOWLEDGMENT_TYPES = Object.freeze(["AUTHENTICATED_ELECTRONIC_SIGN_OFF", "PHYSICAL_DOCUMENT"]);

export const FINANCE_CONFIGURATION_KEYS = Object.freeze({
  LOCAL_MOBILITY_DAILY_LIMIT: "LOCAL_MOBILITY_DAILY_LIMIT",
  UNSUPPORTED_EXPENSE_LIMIT: "UNSUPPORTED_EXPENSE_LIMIT",
  RENDITION_OVERDUE_DAYS: "RENDITION_OVERDUE_DAYS"
});
export const DEFAULT_RENDITION_OVERDUE_DAYS = 10;
export const FINANCE_CONFIGURATION_BEHAVIORS = Object.freeze(["INFORMATION", "WARNING", "FLAG", "BLOCK"]);

export const BUDGET_MODES = Object.freeze(["TRANSITIONAL", "ACTIVE"]);
export const BUDGET_EXCEPTION_STRATEGIES = Object.freeze(["REJECT", "REQUEST_BUDGET_INCREASE", "EXTRAORDINARY_APPROVAL"]);
export const BUDGET_STATUS = Object.freeze({
  NO_BUDGET: "NO_BUDGET",
  AVAILABLE: "AVAILABLE",
  COMMITTED: "COMMITTED",
  DEFERRED: "DEFERRED",
  PARTIALLY_EXECUTED: "PARTIALLY_EXECUTED",
  EXECUTED: "EXECUTED",
  PARTIALLY_PAID: "PARTIALLY_PAID",
  RELEASED: "RELEASED",
  CLOSED: "CLOSED"
});

export const AP_STATUS = Object.freeze({
  OPEN: "OPEN",
  SCHEDULED: "SCHEDULED",
  PAYMENT_FILE_CREATED: "PAYMENT_FILE_CREATED",
  PAYMENT_BOUNCED: "PAYMENT_BOUNCED",
  PARTIALLY_PAID: "PARTIALLY_PAID",
  PAID: "PAID",
  CANCELLED: "CANCELLED"
});

export const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: "VALIDATION_ERROR",
  MISSING_REQUIRED_DOCUMENT: "MISSING_REQUIRED_DOCUMENT",
  XML_AMOUNT_MISMATCH: "XML_AMOUNT_MISMATCH",
  XML_VALIDATION_FAILED: "XML_VALIDATION_FAILED",
  TITLE_REQUIRED: "TITLE_REQUIRED",
  DETAILED_DESCRIPTION_REQUIRED: "DETAILED_DESCRIPTION_REQUIRED",
  BUSINESS_JUSTIFICATION_REQUIRED: "BUSINESS_JUSTIFICATION_REQUIRED",
  NON_APPROVAL_RISK_REQUIRED: "NON_APPROVAL_RISK_REQUIRED",
  INVALID_COST_CENTER: "INVALID_COST_CENTER",
  INVALID_COST_CENTER_LINE: "INVALID_COST_CENTER_LINE",
  QUOTATION_MINIMUM_NOT_MET: "QUOTATION_MINIMUM_NOT_MET",
  QUOTATION_ATTACHMENT_REQUIRED: "QUOTATION_ATTACHMENT_REQUIRED",
  NO_RECOMMENDED_QUOTATION: "NO_RECOMMENDED_QUOTATION",
  MULTIPLE_RECOMMENDED_QUOTATIONS: "MULTIPLE_RECOMMENDED_QUOTATIONS",
  RECOMMENDED_SUPPLIER_MISMATCH: "RECOMMENDED_SUPPLIER_MISMATCH",
  SUPPLIER_SELECTION_REASON_REQUIRED: "SUPPLIER_SELECTION_REASON_REQUIRED",
  SUPPLIER_REJECTED: "SUPPLIER_REJECTED",
  SUPPLIER_INACTIVE: "SUPPLIER_INACTIVE",
  SUPPLIER_NOT_HOMOLOGATED: "SUPPLIER_NOT_HOMOLOGATED",
  DUPLICATE_SUPPLIER: "DUPLICATE_SUPPLIER",
  DUPLICATE_VOUCHER: "DUPLICATE_VOUCHER",
  PURCHASE_ORDER_AMOUNT_EXCEEDED: "PURCHASE_ORDER_AMOUNT_EXCEEDED",
  PURCHASE_ORDER_EXHAUSTED: "PURCHASE_ORDER_EXHAUSTED",
  BATCH_UPLOAD_INVALID: "BATCH_UPLOAD_INVALID",
  BATCH_PROCESSING_FAILED: "BATCH_PROCESSING_FAILED",
  OVERDUE_RENDITION: "OVERDUE_RENDITION",
  PAYMENT_BOUNCED: "PAYMENT_BOUNCED",
  INSUFFICIENT_BUDGET: "INSUFFICIENT_BUDGET",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  ACCOUNTING_PERIOD_CLOSED: "ACCOUNTING_PERIOD_CLOSED",
  ACCOUNTING_PERIOD_MISSING: "ACCOUNTING_PERIOD_MISSING",
  EXCHANGE_RATE_MISSING: "EXCHANGE_RATE_MISSING",
  BANK_DETAILS_MISSING: "BANK_DETAILS_MISSING",
  BANK_ACCOUNT_NOT_ELIGIBLE: "BANK_ACCOUNT_NOT_ELIGIBLE",
  PAYMENT_DESTINATION_LOCKED: "PAYMENT_DESTINATION_LOCKED",
  PROCUREMENT_NOT_APPLICABLE: "PROCUREMENT_NOT_APPLICABLE",
  PROCUREMENT_NOT_READY: "PROCUREMENT_NOT_READY",
  ORDER_KIND_UNDETERMINED: "ORDER_KIND_UNDETERMINED",
  REQUEST_APPROVAL_PENDING: "REQUEST_APPROVAL_PENDING",
  BUDGET_NOT_COMMITTED: "BUDGET_NOT_COMMITTED",
  SUPPLIER_HOMOLOGATION_PENDING: "SUPPLIER_HOMOLOGATION_PENDING",
  SUPPLIER_HOMOLOGATION_OBSERVED: "SUPPLIER_HOMOLOGATION_OBSERVED",
  SUPPLIER_PRV_MISSING: "SUPPLIER_PRV_MISSING",
  QUOTATION_REQUIREMENTS_INCOMPLETE: "QUOTATION_REQUIREMENTS_INCOMPLETE",
  RENDITION_REQUIRED: "RENDITION_REQUIRED",
  MOBILITY_ORIGIN_REQUIRED: "MOBILITY_ORIGIN_REQUIRED",
  MOBILITY_DESTINATION_REQUIRED: "MOBILITY_DESTINATION_REQUIRED",
  MOBILITY_PURPOSE_REQUIRED: "MOBILITY_PURPOSE_REQUIRED",
  UNSUPPORTED_EXPENSE_DESCRIPTION_REQUIRED: "UNSUPPORTED_EXPENSE_DESCRIPTION_REQUIRED",
  UNSUPPORTED_EXPENSE_DECLARATION_REQUIRED: "UNSUPPORTED_EXPENSE_DECLARATION_REQUIRED",
  RENDITION_TOTAL_MISMATCH: "RENDITION_TOTAL_MISMATCH",
  BENEFICIARY_ACKNOWLEDGMENT_REQUIRED: "BENEFICIARY_ACKNOWLEDGMENT_REQUIRED",
  REIMBURSEMENT_BANK_REQUIRED: "REIMBURSEMENT_BANK_REQUIRED",
  REIMBURSEMENT_BANK_PENDING_VERIFICATION: "REIMBURSEMENT_BANK_PENDING_VERIFICATION",
  UNAUTHORIZED_COST_CENTER: "UNAUTHORIZED_COST_CENTER",
  PAYABLE_BLOCKING_OBSERVATION: "PAYABLE_BLOCKING_OBSERVATION",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTEGRATION_NOT_CONFIGURED: "INTEGRATION_NOT_CONFIGURED"
});

export const CLOSED_PERIOD_MESSAGE =
  "The accounting period is closed. Records or modifications are not permitted for this period.";
