export const budgetPlanningSpanish = {
  "Annual only": "Solo anual",
  "Annual + monthly control": "Anual + control mensual",
  "January": "Enero", "February": "Febrero", "March": "Marzo", "April": "Abril", "May": "Mayo", "June": "Junio",
  "July": "Julio", "August": "Agosto", "September": "Septiembre", "October": "Octubre", "November": "Noviembre", "December": "Diciembre",
  "Budget view": "Vista presupuestal",
  "Annual view": "Vista anual",
  "Monthly view": "Vista mensual",
  "Budget year": "Año presupuestal",
  "Month": "Mes",
  "Annual budget": "Presupuesto anual",
  "Annual available": "Disponible anual",
  "Monthly available": "Disponible mensual",
  "Annual budget shortfall": "Déficit del presupuesto anual",
  "Monthly budget shortfall": "Déficit del presupuesto mensual",
  "Annual / monthly limits": "Límites anual / mensual",
  "Budget planning mode": "Modalidad presupuestal",
  "Pending allocation": "Pendiente de asignación",
  "Annual budget plan": "Plan presupuestal anual",
  "Create annual budget": "Crear presupuesto anual",
  "Create budget plan": "Crear plan presupuestal",
  "View annual plan": "Ver plan anual",
  "Legacy allocations": "Asignaciones existentes",
  "Legacy allocation": "Asignación existente",
  "Undated legacy balance": "Saldo histórico sin año",
  "LINKED_ANNUAL_PLAN": "PLAN ANUAL VINCULADO",
  "Monthly distribution": "Distribución mensual",
  "Monthly distribution and activity": "Distribución y actividad mensual",
  "Distribute equally": "Distribuir en partes iguales",
  "Custom distribution": "Distribución personalizada",
  "Expense account": "Cuenta de gasto",
  "Adjust budget": "Ajustar presupuesto",
  "Audited budget adjustment": "Ajuste presupuestal con historial",
  "Adjustment type": "Tipo de ajuste",
  "Adjustment amount": "Monto del ajuste",
  "Transfer between months": "Transferir entre meses",
  "Allocate annual reserve": "Asignar reserva anual",
  "Record approved annual increase": "Registrar ampliación anual aprobada",
  "From month": "Mes de origen",
  "To month": "Mes de destino",
  "Reason / approval reference": "Motivo / referencia de aprobación",
  "Save adjustment": "Guardar ajuste",
  "Budget adjustment history": "Historial de ajustes presupuestales",
  "Budget created": "Presupuesto creado",
  "Annual increase": "Ampliación anual",
  "Monthly activity is tracked against the annual limit.": "La actividad mensual se controla contra el límite anual.",
  "Each request must fit both the annual and monthly limits. Unused amounts stay in their month until transferred.": "Cada solicitud debe respetar los límites anual y mensual. Los montos no utilizados permanecen en su mes hasta ser transferidos.",
  "Only unused budget can be transferred. The annual total remains unchanged.": "Solo puede transferirse presupuesto no utilizado. El total anual se mantiene.",
  "Record the approval reference. For monthly plans, the increase remains pending allocation until assigned to a month.": "Registre la referencia de aprobación. En planes mensuales, la ampliación queda pendiente hasta asignarla a un mes.",
  "Allocate part of the undistributed annual amount to the selected month.": "Asigne parte del monto anual no distribuido al mes seleccionado.",
  "Create a yearly budget for a Cost Center, expense account, and optional project. Existing allocations and recorded activity remain unchanged.": "Cree un presupuesto anual por centro de costo, cuenta de gasto y proyecto opcional. Se conservan las asignaciones y la actividad registradas.",
  "Legacy Cost Center balances have no budget year and are excluded from selected-period totals.": "Los saldos históricos de centros de costo no tienen año presupuestal y se excluyen de los totales del período seleccionado.",
  "Annual-only plans show monthly activity without a monthly limit. View their annual plan for available budget.": "Los planes solo anuales muestran actividad mensual sin límite mensual. Consulte su plan anual para ver el disponible.",
  "Enter a valid budget amount with at most two decimal places.": "Ingrese un monto presupuestal válido con hasta dos decimales.",
  "The budget amount is too large.": "El monto presupuestal es demasiado grande.",
  "A reason of at most 2000 characters is required.": "Se requiere un motivo de hasta 2000 caracteres.",
  "Select a valid month.": "Seleccione un mes válido.",
  "A valid adjustment identifier is required.": "Se requiere un identificador de ajuste válido.",
  "Select a valid budget plan.": "Seleccione un plan presupuestal válido.",
  "Budget plan not found.": "No se encontró el plan presupuestal.",
  "Enter a budget year between 2000 and 2199.": "Ingrese un año presupuestal entre 2000 y 2199.",
  "Select a valid budget year or month.": "Seleccione un año o mes presupuestal válido.",
  "Select a valid budget planning mode.": "Seleccione una modalidad presupuestal válida.",
  "Select a Cost Center and expense account.": "Seleccione un centro de costo y una cuenta de gasto.",
  "Enter a project of at most 150 characters.": "Ingrese un proyecto de hasta 150 caracteres.",
  "The annual budget must be greater than zero.": "El presupuesto anual debe ser mayor que cero.",
  "Select an active Cost Center and expense account.": "Seleccione un centro de costo y una cuenta de gasto activos.",
  "An allocation already exists for this year and dimension. Existing allocations remain unchanged; choose another year or dimension.": "Ya existe una asignación para este año y dimensión. Se conserva la asignación existente; seleccione otro año o dimensión.",
  "This dimension already has budget activity in the selected year. Create a plan for a new year to preserve its recorded usage.": "Esta dimensión ya tiene actividad presupuestal en el año seleccionado. Cree un plan para un nuevo año para conservar el consumo registrado.",
  "Choose equal distribution or enter all twelve monthly amounts.": "Elija distribución igualitaria o ingrese los doce montos mensuales.",
  "Monthly allocations cannot exceed the annual budget.": "Las asignaciones mensuales no pueden superar el presupuesto anual.",
  "A budget already exists for this year and dimension.": "Ya existe un presupuesto para este año y dimensión.",
  "The budget changed. Refresh it before making an adjustment.": "El presupuesto cambió. Actualícelo antes de realizar un ajuste.",
  "The adjustment amount must be greater than zero.": "El monto del ajuste debe ser mayor que cero.",
  "Select a valid budget adjustment.": "Seleccione un ajuste presupuestal válido.",
  "Monthly adjustments require monthly budget control.": "Los ajustes mensuales requieren control presupuestal mensual.",
  "Choose two different months.": "Elija dos meses diferentes.",
  "The source month has insufficient uncommitted budget.": "El mes de origen no tiene suficiente presupuesto sin comprometer.",
  "The annual reserve is insufficient for this allocation.": "La reserva anual es insuficiente para esta asignación.",
  "Only Budget or Admin can manage budget plans.": "Solo Presupuesto o Administración pueden gestionar planes presupuestales.",
  "Manage this linked budget through Budget Control and its audited adjustments.": "Gestione este presupuesto vinculado desde Control Presupuestal y sus ajustes con historial.",
  "A linked annual budget already controls this dimension. Use Budget Control to adjust it.": "Un presupuesto anual vinculado ya controla esta dimensión. Ajústelo desde Control Presupuestal.",
  "Budget availability changed. Refresh and retry the operation.": "El disponible presupuestal cambió. Actualice y vuelva a intentar la operación.",
  "The request needs a valid month within the budget year.": "La solicitud requiere un mes válido dentro del año presupuestal."
};
