export default {
  "Funds are reserved before posting the advance. The actual expense is recognized at rendition. This preview does not reserve funds.": "Los fondos se reservan antes de contabilizar el adelanto. El gasto real se reconoce al rendir. Esta vista previa no reserva fondos.",
  "Workspace help": "Ayuda del espacio de trabajo",
  "Accessibility settings": "Opciones de accesibilidad",
  "Your workspace tour": "Recorrido de su espacio de trabajo",
  "Reduce motion": "Reducir animaciones",
  "High contrast": "Alto contraste",
  "Larger text": "Texto más grande",
  "Your system motion preference is always respected.": "Siempre se respeta la preferencia de movimiento de su dispositivo.",
  "This workspace shows the information and actions available to your role.": "Este espacio muestra la información y las acciones disponibles para su rol.",
  "Open workspace": "Abrir espacio de trabajo",
  "Keyboard shortcuts": "Atajos de teclado",
  "Start workspace tour": "Iniciar recorrido",
  "Restart workspace tour": "Reiniciar recorrido",
  "Finish tour": "Finalizar recorrido",
  "Open a request to see its current stage, required documents and the actions available to you. Payment and rendition progress are shown separately.": "Abra una solicitud para ver su etapa actual, los documentos requeridos y las acciones disponibles. El avance del pago y la rendición se muestran por separado.",
  "Review the payment destination and currency before generating a BBVA file. Confirm payment only after receiving bank evidence.": "Revise el destino del pago y la moneda antes de generar el archivo BBVA. Confirme el pago solo después de recibir la evidencia bancaria.",
  "Review fiscal evidence and the open accounting period before posting. Open a request to resolve missing documents.": "Revise la evidencia fiscal y el período contable abierto antes de contabilizar. Abra la solicitud para resolver documentos pendientes.",
  "Open the supporting documents, review the SLA and record your decision. The next approver follows the stored approval route.": "Abra los documentos de sustento, revise el plazo y registre su decisión. El siguiente aprobador corresponde a la ruta guardada.",
  "Review availability and commitments in the selected period. Paid amounts are shown separately and must not be added to executed amounts.": "Revise la disponibilidad y los compromisos del período seleccionado. Los importes pagados se muestran por separado y no se suman a los ejecutados.",
  "Select a KPI or chart to explore its records. Use Search to find work available to your role. Saved views and display preferences apply only to your workspace.": "Seleccione un indicador o gráfico para explorar sus registros. Use Buscar para encontrar el trabajo disponible para su rol. Las vistas y preferencias se guardan en su espacio de trabajo.",
  "Last refreshed": "Última actualización",
  "Just now": "Ahora mismo",
  "min ago": "min atrás",
  "Overdue by": "Vencido hace",
  "Due in": "Vence en",
  "Each bar is a share of assigned budget. Paid is not added to executed.": "Cada barra representa una proporción del presupuesto asignado. Lo pagado no se suma a lo ejecutado.",
  "Approval journey": "Ruta de aprobación",
  "Attention indicators": "Indicadores de atención",
  "No alerts reported for the current dashboard scope.": "No hay alertas en el alcance actual del panel.",
  "Based on the current dashboard alerts, not a financial certification.": "Basado en las alertas actuales del panel; no constituye una certificación financiera.",
  "Drop files here or choose files": "Arrastre los archivos aquí o selecciónelos",
  "Selected locally. Upload completes when you save.": "Seleccionado en este dispositivo. La carga se completa al guardar.",
  "Choose one file at a time.": "Seleccione un archivo a la vez.",
  "Empty files cannot be uploaded.": "No se pueden cargar archivos vacíos.",
  "This file type is not accepted. Check the allowed formats.": "No se acepta este tipo de archivo. Revise los formatos permitidos.",
  "Recent work": "Trabajo reciente",
  "Financial overview": "Resumen financiero",
  "Widget hidden.": "Se ocultó el panel.",
  "Undo": "Deshacer",
  "Customize dashboard": "Personalizar panel",
  "Restore default layout": "Restaurar diseño inicial",
  "Move up": "Mover arriba",
  "Move down": "Mover abajo",
  "Show": "Mostrar",
  "Hide": "Ocultar",
  "Recent activity for you": "Su actividad reciente",
  "Latest notifications · refreshes every 30 seconds while open": "Últimas notificaciones · se actualizan cada 30 segundos mientras esté abierto",
  "Budget availability by cost center": "Disponibilidad presupuestal por centro de costo",
  "Select a cost center to review its requests. Values follow the current report filters.": "Seleccione un centro de costo para revisar sus solicitudes. Los valores respetan los filtros del reporte.",
  "No budget allocations in this scope.": "No hay asignaciones presupuestales en este alcance.",
  "Annual plan only": "Solo plan anual",
  "Presentation mode": "Modo presentación",
  "Management presentation": "Presentación de Gerencia",
  "Auto-play": "Reproducir automáticamente",
  "Pause": "Pausar",
  "Full screen": "Pantalla completa",
  "Fullscreen is unavailable in this browser.": "La pantalla completa no está disponible en este navegador.",
  "Payment calendar": "Calendario de pagos",
  "Calendar view": "Vista del calendario",
  "Month": "Mes",
  "Week": "Semana",
  "Scheduled payments use the scheduled date. Unscheduled payments use the due date. Currencies are never combined.": "Los pagos programados usan la fecha programada. Los demás usan su vencimiento. Las monedas se muestran por separado.",
  "Loading all payment pages...": "Cargando todas las páginas de pagos...",
  "No payments on these dates.": "No hay pagos en estas fechas.",
  "Payments without dates remain in the payment queue.": "Los pagos sin fecha permanecen en la cola de pagos.",
  "Too many records. Narrow the date range before viewing the calendar.": "Hay demasiados registros para mostrar el calendario completo. Revise la cola de pagos.",
  "Panel width": "Ancho del panel",
  "Notification filters": "Filtros de notificaciones",
  "Unread": "No leídas",
  "Other": "Otras",
  "Help with this request": "Ayuda con esta solicitud",
  "Actions are checked again by the server when you submit them.": "El servidor vuelve a validar las acciones al enviarlas.",
  "Completed requirements": "Requisitos completos",
  "Upload sent. Validating and saving...": "Carga enviada. Validando y guardando...",
  "Filters cleared.": "Filtros restablecidos.",
  "Lowest price in this currency": "Menor precio en esta moneda",
  "above lowest in this currency": "sobre el menor precio en esta moneda",
  "View chart": "Ver gráfico",
  "Budget consumption": "Consumo presupuestal",
  "Search requests, suppliers, RUC, invoices...": "Buscar solicitudes, proveedores, RUC, comprobantes...",
  "Some search sources are unavailable. Try again.": "Algunas fuentes de búsqueda no están disponibles. Inténtelo de nuevo.",
  "Invoice / CXP": "Comprobante / CXP",
  "Active purchase order": "Orden de compra activa",
  "Payment batch": "Lote de pagos",
  "Your workspace is ready.": "Su espacio de trabajo está listo.",
  "Use the help button for a short tour and keyboard shortcuts.": "Use el botón de ayuda para ver un breve recorrido y los atajos de teclado.",
  "Got it": "Entendido",
  "Open next step": "Abrir siguiente paso",
  "Technical evidence": "Evidencia técnica",
  "Recent notifications": "Notificaciones recientes"
};
