// Display copy only. Status keys, API values and financial decisions are unchanged.
export const umaCopy = {
  "Financial Control": "Financial management",
  "Monitor and control assigned, committed, executed, paid, and available budget using the same dimensional ledger as workflow transactions.": "Follow your annual plan and each month’s available budget, commitments and spending.",
  "Period, Cost Center, expense classification, and project remain visible together.": "Review budgets by period, Cost Center, expense account and project.",
  "Read-only result from the existing Budget service. No funds are reserved here.": "Budget estimate. Funds are reserved after the required approvals.",
  "This is a current read-only calculation; the authoritative commitment remains in the budget ledger.": "Current budget availability. Review the recorded commitment in Financial records.",
  "The backend revalidates permission, period, status, documents, supplier, fiscal, and budget controls.": "Available actions depend on your role and the request’s current stage.",
  "The system derives every gate from the approved request and controlled master data.": "Review what is ready and what must be resolved before issuing the order.",
  "Original evidence is protected and fiscal amounts come from server-side XML parsing.": "Review supporting documents and the amounts read from the invoice XML.",
  "All accounting dimensions and immutable commercial totals are shown per line.": "Review each item’s quantity, amount, Cost Center and expense account.",
  "Commercial values and accounting dimensions remain on the same request line.": "Enter each item or service with its amount, Cost Center and expense account.",
  "Official request identity, responsible area and business need.": "Who requested this purchase and why it is needed.",
  "Budget, purchase order, CXP, journals, bank batches, payment, and reconciliation remain independently traceable.": "Follow the commitment, order, invoices and payments linked to this request.",
  "Application audit records are append-only.": "Recorded changes are retained in the request history.",
  "Schedule each CXP independently, create bank instructions, confirm execution, isolate bounced transfers, and reconcile paid requests.": "Prepare payment instructions, confirm bank payments and resolve returned transfers.",
  "The batch is generated from selected CXP records, not from one request-level payable.": "Choose the bank, currency and payment date, then select the invoices to include.",
  "Every batch retains its checksum, adapter mode, CXP items, and generation user.": "Review and download previously generated bank instructions.",
  "Interactive institutional analysis using current request, budget, Accounting, CXP, Treasury, rendition, and reconciliation data.": "Explore university spending, budget availability, approvals and payments.",
  "Immutable audit": "Activity history",
  "Payment destination snapshot": "Recorded payment destination",
  "PENDING_VALIDATION": "Pending validation", "BORRADOR": "Draft", "EN_VALIDACION": "Under review",
  "ENVIADO": "Submitted", "PENDIENTE_APROBACION": "Pending approval", "OBSERVADO": "Needs correction",
  "DEVUELTO": "Returned", "RECHAZADO": "Rejected", "APROBADO_DIRECTOR": "Director approved",
  "APROBADO_VICERRECTOR": "Vice Rector approved", "COMPROMISO_PRESUPUESTAL": "Budget committed",
  "CONTABILIZADO": "Posted", "PROVISIONADO_CXP": "Accounts payable recorded", "PROGRAMADO": "Scheduled",
  "TXT_GENERADO": "Bank file generated", "PAGADO": "Paid", "CONCILIADO": "Reconciled",
  "RENDICION_PENDIENTE": "Rendition pending", "CERRADO": "Closed", "ANULADO": "Cancelled",
  "AVAILABLE": "Available", "COMMITTED": "Committed", "EXECUTED": "Executed", "PAID": "Paid",
  "APPROVED": "Approved", "REJECTED": "Rejected", "PENDING": "Pending", "CLOSED": "Closed",
  "ACTIVE": "Active", "INACTIVE": "Inactive", "VERIFIED": "Verified", "HOMOLOGATED": "Homologated",
  "PARTIALLY_PAID": "Partially paid", "PARTIALLY_EXECUTED": "Partially executed",
  "PAYMENT_FILE_CREATED": "Bank file generated", "PAYMENT_BOUNCED": "Payment returned",
  "PAGO_REBOTADO": "Payment returned", "PAGADO_CERRADO": "Paid and closed",
  "INSUFFICIENT": "Insufficient budget", "NO_BUDGET": "Transitional budget",
  "LINKED_ANNUAL_PLAN": "Annual budget plan", "DIMENSIONAL_ALLOCATION": "Legacy allocation",
  "TRANSITIONAL_COST_CENTER": "Cost Center balance", "TRANSITIONAL": "Transitional"
};

export const umaSpanish = {
  "100% Advance": "100% Adelanto", "100% On Delivery": "100% Contra entrega", "Advance + Balance": "Adelanto + Saldo",
  "Pay the full amount before starting": "Paga el importe completo antes de comenzar",
  "Pay the full amount on delivery": "Paga el importe completo contra entrega",
  "Choose an advance, pay the rest later": "Elige el adelanto y paga el saldo después",
  "Advance percentage slider": "Control del porcentaje de adelanto",
  "Enter a valid advance percentage": "Ingresa un porcentaje de adelanto válido",
  "Quick advance percentages": "Porcentajes rápidos de adelanto",
  "Custom": "Personalizado", "Additional terms (optional)": "Condiciones adicionales (opcional)",
  "Saved terms are retained until you choose a payment option above.": "Se conservan las condiciones guardadas hasta que elijas una de las opciones de pago de arriba.",
  "Unit price already includes IGV (18%)": "El precio unitario ya incluye IGV (18%)",
  "Final total": "Total final", "Subtotal": "Subtotal", "Included": "Incluido", "Request total": "Total de la solicitud", "Item": "Ítem",
  "Enter the quantity and unit price. We calculate IGV and the final total for you.": "Ingresa la cantidad y el precio unitario. Calculamos el IGV y el total final por ti.",
  "Expense account for these items": "Cuenta de gasto para estos ítems",
  "Choose once for all items. A single eligible account is selected automatically.": "Elige una vez para todos los ítems. Si solo hay una cuenta permitida, se selecciona automáticamente.",
  "Adjust budget allocation": "Ajustar asignación presupuestal",
  "Items inherit the request's cost center and expense account. Adjust only when an item uses a different budget.": "Los ítems usan el centro de costos y la cuenta de gasto de la solicitud. Ajusta solo si un ítem usa otro presupuesto.",
  "Previously saved amounts are retained. Change quantity, unit price or the IGV option to use automatic calculation.": "Se conservan los importes guardados anteriormente. Cambia la cantidad, el precio unitario o la opción de IGV para usar el cálculo automático.",
  "Select a unit of measure.": "Selecciona una unidad de medida.",
  "Quantity supports up to 8 decimal places.": "La cantidad admite hasta 8 decimales.",
  "The item amount is too large.": "El importe del ítem es demasiado grande.",
  "Choose whether the unit price includes IGV.": "Indica si el precio unitario incluye IGV.",
  "UNIT": "UNIDAD", "SERVICE": "SERVICIO", "HOUR": "HORA", "DAY": "DÍA", "MONTH": "MES", "SET": "JUEGO", "BOX": "CAJA", "KG": "KG", "LITER": "LITRO", "METER": "METRO",
  "Scroll horizontally to see all columns.": "Desplázate horizontalmente para ver todas las columnas.",
  "Financial management": "Gestión financiera", "Planning and reports": "Planificación e informes",
  "UMA home": "Inicio UMA", "Skip to main content": "Ir al contenido principal", "Account menu": "Menú de cuenta",
  "Welcome to UMA": "Bienvenido a UMA", "Sign in with your university account.": "Ingresa con tu cuenta universitaria.",
  "One place for your financial work.": "Tu gestión financiera, en un solo lugar.",
  "Requests, approvals and budgets. Connected from the first step to payment.": "Solicitudes, aprobaciones y presupuestos. Conectados desde el primer paso hasta el pago.",
  "Show password": "Mostrar contraseña", "Hide password": "Ocultar contraseña",
  "Card view": "Vista de tarjetas", "Table view": "Vista de tabla", "Active filters": "Filtros activos",
  "Scrollable results": "Resultados desplazables", "No records yet": "Aún no hay registros",
  "No matching results": "No se encontraron resultados", "Try a different search or clear your filters.": "Prueba otra búsqueda o limpia los filtros.",
  "Enter a value to continue.": "Ingresa un valor para continuar.", "Your workspace": "Tu espacio de trabajo",
  "Keep university operations moving": "Mantén en marcha la gestión universitaria",
  "Review requests and the items that need your team’s attention.": "Revisa las solicitudes y los asuntos que necesitan la atención de tu equipo.",
  "View requests": "Ver solicitudes", "Your next request starts here": "Tu próxima solicitud empieza aquí",
  "Prepare a request or continue work saved in your drafts.": "Prepara una solicitud o continúa con tus borradores guardados.",
  "Your decisions move work forward": "Tus decisiones hacen avanzar el trabajo",
  "Review the oldest pending requests and their supporting documents.": "Revisa las solicitudes pendientes más antiguas y sus documentos de sustento.",
  "Review approvals": "Revisar aprobaciones", "Keep the accounts up to date": "Mantén las cuentas al día",
  "Review pending entries, documents and accounting observations.": "Revisa los asientos pendientes, documentos y observaciones contables.",
  "Open Accounting": "Ir a Contabilidad", "A clear view of upcoming payments": "Una vista clara de los próximos pagos",
  "Review payment destinations, scheduled items and bank confirmations.": "Revisa las cuentas de destino, los pagos programados y las confirmaciones bancarias.",
  "Open Treasury": "Ir a Tesorería", "Plan the year. Follow each month.": "Planifica el año. Sigue cada mes.",
  "Review annual availability, monthly allocations and budget exceptions.": "Revisa el saldo anual, las asignaciones mensuales y las excepciones presupuestales.",
  "Open Budget Control": "Ir a Control presupuestal", "See the institution’s financial position": "Conoce la situación financiera de la universidad",
  "Explore spending, budget availability and work awaiting completion.": "Consulta los gastos, el saldo presupuestal y el trabajo pendiente.",
  "Open reports": "Ver informes", "Supplier / beneficiary": "Proveedor / beneficiario",
  "Current status": "Estado actual", "Request sections": "Secciones de la solicitud", "Financial records": "Registros financieros",
  "Actions and history": "Acciones e historial", "Step {step} of {total}": "Paso {step} de {total}",
  "Fields marked * are required.": "Los campos con * son obligatorios.", "Ready to upload": "Listo para cargar",
  "Files attached": "Archivos adjuntos", "Required document": "Documento obligatorio", "Optional document": "Documento opcional",
  "Distributed to months": "Distribuido entre los meses", "Selected month": "Mes seleccionado",
  "Payment stages": "Etapas del pago", "Prepare bank file": "Preparar archivo bancario", "Confirm payments": "Confirmar pagos",
  "Returned payments": "Pagos devueltos", "Reconcile": "Conciliar", "Bank file history": "Historial de archivos bancarios",
  "Print report": "Imprimir informe", "Showing report for": "Informe para", "All periods": "Todos los periodos",
  "Applied filters": "Filtros aplicados", "Activity history": "Historial de actividad", "Recorded payment destination": "Cuenta de destino registrada",
  "Follow your annual plan and each month’s available budget, commitments and spending.": "Sigue tu plan anual y el saldo disponible, compromisos y gastos de cada mes.",
  "Review budgets by period, Cost Center, expense account and project.": "Consulta los presupuestos por periodo, centro de costos, cuenta de gasto y proyecto.",
  "Budget estimate. Funds are reserved after the required approvals.": "Estimación presupuestal. Los fondos se reservan después de las aprobaciones requeridas.",
  "Current budget availability. Review the recorded commitment in Financial records.": "Saldo presupuestal actual. Consulta el compromiso registrado en Registros financieros.",
  "Available actions depend on your role and the request’s current stage.": "Las acciones disponibles dependen de tu rol y de la etapa actual de la solicitud.",
  "Review what is ready and what must be resolved before issuing the order.": "Revisa qué está listo y qué debe resolverse antes de emitir la orden.",
  "Review supporting documents and the amounts read from the invoice XML.": "Revisa los documentos de sustento y los importes leídos del XML de la factura.",
  "Review each item’s quantity, amount, Cost Center and expense account.": "Revisa la cantidad, el importe, el centro de costos y la cuenta de gasto de cada ítem.",
  "Enter each item or service with its amount, Cost Center and expense account.": "Ingresa cada ítem o servicio con su importe, centro de costos y cuenta de gasto.",
  "Who requested this purchase and why it is needed.": "Quién solicitó esta compra y por qué se necesita.",
  "Follow the commitment, order, invoices and payments linked to this request.": "Consulta el compromiso, la orden, las facturas y los pagos de esta solicitud.",
  "Recorded changes are retained in the request history.": "Los cambios registrados se conservan en el historial de la solicitud.",
  "Prepare payment instructions, confirm bank payments and resolve returned transfers.": "Prepara instrucciones de pago, confirma los pagos bancarios y resuelve las transferencias devueltas.",
  "Choose the bank, currency and payment date, then select the invoices to include.": "Elige el banco, la moneda y la fecha de pago; luego selecciona las facturas que deseas incluir.",
  "Review and download previously generated bank instructions.": "Revisa y descarga las instrucciones bancarias generadas anteriormente.",
  "Explore university spending, budget availability, approvals and payments.": "Consulta los gastos, el saldo presupuestal, las aprobaciones y los pagos de la universidad.",
  "Pending validation": "Validación pendiente", "Draft": "Borrador", "Under review": "En revisión",
  "Submitted": "Enviado", "Pending approval": "Aprobación pendiente", "Needs correction": "Requiere corrección",
  "Returned": "Devuelto", "Rejected": "Rechazado", "Director approved": "Aprobado por Dirección",
  "Vice Rector approved": "Aprobado por Vicerrectorado", "Budget committed": "Presupuesto comprometido",
  "Posted": "Contabilizado", "Accounts payable recorded": "Cuenta por pagar registrada", "Scheduled": "Programado",
  "Bank file generated": "Archivo bancario generado", "Paid": "Pagado", "Reconciled": "Conciliado",
  "Rendition pending": "Rendición pendiente", "Closed": "Cerrado", "Cancelled": "Anulado",
  "Approved": "Aprobado", "Pending": "Pendiente", "Active": "Activo", "Inactive": "Inactivo",
  "Verified": "Verificado", "Homologated": "Homologado", "Partially paid": "Pagado parcialmente",
  "Partially executed": "Ejecutado parcialmente", "Payment returned": "Pago devuelto", "Paid and closed": "Pagado y cerrado",
  "Insufficient budget": "Presupuesto insuficiente", "Transitional budget": "Presupuesto transitorio",
  "Annual budget plan": "Plan presupuestal anual", "Cost Center balance": "Saldo del centro de costos", "Transitional": "Transitorio"
};
